
package org.onvif.ver20.analytics.wsdl;

import java.util.List;
import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.namespace.QName;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;
import org.onvif.ver10.schema.Config;
import org.onvif.ver10.schema.SupportedRules;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RuleEnginePort", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl")
@XmlSeeAlso({
    org.oasis_open.docs.wsn.b_2.ObjectFactory.class,
    org.oasis_open.docs.wsn.t_1.ObjectFactory.class,
    org.oasis_open.docs.wsrf.bf_2.ObjectFactory.class,
    org.onvif.ver10.schema.ObjectFactory.class,
    org.onvif.ver20.analytics.wsdl.ObjectFactory.class,
    org.w3._2003._05.soap_envelope.ObjectFactory.class,
    org.w3._2004._08.xop.include.ObjectFactory.class,
    org.w3._2005._05.xmlmime.ObjectFactory.class,
    org.w3._2005._08.addressing.ObjectFactory.class
})
public interface RuleEnginePort {


    /**
     * 
     * 				List all rules that are supported by the given VideoAnalyticsConfiguration.
     * 				The result of this method may depend on the overall Video analytics configuration of the device,
     * 				which is available via the current set of profiles. 
     * 			
     * 
     * @param configurationToken
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver20.analytics.wsdl.GetSupportedRulesResponse>
     */
    @WebMethod(operationName = "GetSupportedRules", action = "http://www.onvif.org/ver20/analytics/wsdl/GetSupportedRules")
    @RequestWrapper(localName = "GetSupportedRules", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", className = "org.onvif.ver20.analytics.wsdl.GetSupportedRules")
    @ResponseWrapper(localName = "GetSupportedRulesResponse", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", className = "org.onvif.ver20.analytics.wsdl.GetSupportedRulesResponse")
    public Response<GetSupportedRulesResponse> getSupportedRulesAsync(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl")
        String configurationToken);

    /**
     * 
     * 				List all rules that are supported by the given VideoAnalyticsConfiguration.
     * 				The result of this method may depend on the overall Video analytics configuration of the device,
     * 				which is available via the current set of profiles. 
     * 			
     * 
     * @param configurationToken
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetSupportedRules", action = "http://www.onvif.org/ver20/analytics/wsdl/GetSupportedRules")
    @RequestWrapper(localName = "GetSupportedRules", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", className = "org.onvif.ver20.analytics.wsdl.GetSupportedRules")
    @ResponseWrapper(localName = "GetSupportedRulesResponse", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", className = "org.onvif.ver20.analytics.wsdl.GetSupportedRulesResponse")
    public Future<?> getSupportedRulesAsync(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl")
        String configurationToken,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetSupportedRulesResponse> asyncHandler);

    /**
     * 
     * 				List all rules that are supported by the given VideoAnalyticsConfiguration.
     * 				The result of this method may depend on the overall Video analytics configuration of the device,
     * 				which is available via the current set of profiles. 
     * 			
     * 
     * @param configurationToken
     * @return
     *     returns org.onvif.ver10.schema.SupportedRules
     */
    @WebMethod(operationName = "GetSupportedRules", action = "http://www.onvif.org/ver20/analytics/wsdl/GetSupportedRules")
    @WebResult(name = "SupportedRules", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl")
    @RequestWrapper(localName = "GetSupportedRules", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", className = "org.onvif.ver20.analytics.wsdl.GetSupportedRules")
    @ResponseWrapper(localName = "GetSupportedRulesResponse", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", className = "org.onvif.ver20.analytics.wsdl.GetSupportedRulesResponse")
    public SupportedRules getSupportedRules(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl")
        String configurationToken);

    /**
     * 
     * @param rule
     * @param configurationToken
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver20.analytics.wsdl.CreateRulesResponse>
     */
    @WebMethod(operationName = "CreateRules", action = "http://www.onvif.org/ver20/analytics/wsdl/CreateRules")
    @RequestWrapper(localName = "CreateRules", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", className = "org.onvif.ver20.analytics.wsdl.CreateRules")
    @ResponseWrapper(localName = "CreateRulesResponse", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", className = "org.onvif.ver20.analytics.wsdl.CreateRulesResponse")
    public Response<CreateRulesResponse> createRulesAsync(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl")
        String configurationToken,
        @WebParam(name = "Rule", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl")
        List<Config> rule);

    /**
     * 
     * @param rule
     * @param configurationToken
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "CreateRules", action = "http://www.onvif.org/ver20/analytics/wsdl/CreateRules")
    @RequestWrapper(localName = "CreateRules", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", className = "org.onvif.ver20.analytics.wsdl.CreateRules")
    @ResponseWrapper(localName = "CreateRulesResponse", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", className = "org.onvif.ver20.analytics.wsdl.CreateRulesResponse")
    public Future<?> createRulesAsync(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl")
        String configurationToken,
        @WebParam(name = "Rule", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl")
        List<Config> rule,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<CreateRulesResponse> asyncHandler);

    /**
     * 
     * @param rule
     * @param configurationToken
     */
    @WebMethod(operationName = "CreateRules", action = "http://www.onvif.org/ver20/analytics/wsdl/CreateRules")
    @RequestWrapper(localName = "CreateRules", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", className = "org.onvif.ver20.analytics.wsdl.CreateRules")
    @ResponseWrapper(localName = "CreateRulesResponse", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", className = "org.onvif.ver20.analytics.wsdl.CreateRulesResponse")
    public void createRules(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl")
        String configurationToken,
        @WebParam(name = "Rule", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl")
        List<Config> rule);

    /**
     * 
     * 				Remove one or more rules from a VideoAnalyticsConfiguration.
     * 			
     * 
     * @param ruleName
     * @param configurationToken
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver20.analytics.wsdl.DeleteRulesResponse>
     */
    @WebMethod(operationName = "DeleteRules", action = "http://www.onvif.org/ver20/analytics/wsdl/DeleteRules")
    @RequestWrapper(localName = "DeleteRules", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", className = "org.onvif.ver20.analytics.wsdl.DeleteRules")
    @ResponseWrapper(localName = "DeleteRulesResponse", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", className = "org.onvif.ver20.analytics.wsdl.DeleteRulesResponse")
    public Response<DeleteRulesResponse> deleteRulesAsync(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl")
        String configurationToken,
        @WebParam(name = "RuleName", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl")
        List<String> ruleName);

    /**
     * 
     * 				Remove one or more rules from a VideoAnalyticsConfiguration.
     * 			
     * 
     * @param ruleName
     * @param configurationToken
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "DeleteRules", action = "http://www.onvif.org/ver20/analytics/wsdl/DeleteRules")
    @RequestWrapper(localName = "DeleteRules", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", className = "org.onvif.ver20.analytics.wsdl.DeleteRules")
    @ResponseWrapper(localName = "DeleteRulesResponse", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", className = "org.onvif.ver20.analytics.wsdl.DeleteRulesResponse")
    public Future<?> deleteRulesAsync(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl")
        String configurationToken,
        @WebParam(name = "RuleName", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl")
        List<String> ruleName,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<DeleteRulesResponse> asyncHandler);

    /**
     * 
     * 				Remove one or more rules from a VideoAnalyticsConfiguration.
     * 			
     * 
     * @param ruleName
     * @param configurationToken
     */
    @WebMethod(operationName = "DeleteRules", action = "http://www.onvif.org/ver20/analytics/wsdl/DeleteRules")
    @RequestWrapper(localName = "DeleteRules", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", className = "org.onvif.ver20.analytics.wsdl.DeleteRules")
    @ResponseWrapper(localName = "DeleteRulesResponse", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", className = "org.onvif.ver20.analytics.wsdl.DeleteRulesResponse")
    public void deleteRules(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl")
        String configurationToken,
        @WebParam(name = "RuleName", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl")
        List<String> ruleName);

    /**
     * 
     * 				List the currently assigned set of rules of a VideoAnalyticsConfiguration.
     * 			
     * 
     * @param configurationToken
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver20.analytics.wsdl.GetRulesResponse>
     */
    @WebMethod(operationName = "GetRules", action = "http://www.onvif.org/ver20/analytics/wsdl/GetRules")
    @RequestWrapper(localName = "GetRules", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", className = "org.onvif.ver20.analytics.wsdl.GetRules")
    @ResponseWrapper(localName = "GetRulesResponse", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", className = "org.onvif.ver20.analytics.wsdl.GetRulesResponse")
    public Response<GetRulesResponse> getRulesAsync(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl")
        String configurationToken);

    /**
     * 
     * 				List the currently assigned set of rules of a VideoAnalyticsConfiguration.
     * 			
     * 
     * @param configurationToken
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetRules", action = "http://www.onvif.org/ver20/analytics/wsdl/GetRules")
    @RequestWrapper(localName = "GetRules", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", className = "org.onvif.ver20.analytics.wsdl.GetRules")
    @ResponseWrapper(localName = "GetRulesResponse", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", className = "org.onvif.ver20.analytics.wsdl.GetRulesResponse")
    public Future<?> getRulesAsync(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl")
        String configurationToken,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetRulesResponse> asyncHandler);

    /**
     * 
     * 				List the currently assigned set of rules of a VideoAnalyticsConfiguration.
     * 			
     * 
     * @param configurationToken
     * @return
     *     returns java.util.List<org.onvif.ver10.schema.Config>
     */
    @WebMethod(operationName = "GetRules", action = "http://www.onvif.org/ver20/analytics/wsdl/GetRules")
    @WebResult(name = "Rule", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl")
    @RequestWrapper(localName = "GetRules", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", className = "org.onvif.ver20.analytics.wsdl.GetRules")
    @ResponseWrapper(localName = "GetRulesResponse", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", className = "org.onvif.ver20.analytics.wsdl.GetRulesResponse")
    public List<Config> getRules(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl")
        String configurationToken);

    /**
     * 
     * 				Return the options for the supported rules that specify an Option attribute.
     * 			
     * 
     * @param ruleType
     * @param configurationToken
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver20.analytics.wsdl.GetRuleOptionsResponse>
     */
    @WebMethod(operationName = "GetRuleOptions", action = "http://www.onvif.org/ver20/analytics/wsdl/GetRuleOptions")
    @RequestWrapper(localName = "GetRuleOptions", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", className = "org.onvif.ver20.analytics.wsdl.GetRuleOptions")
    @ResponseWrapper(localName = "GetRuleOptionsResponse", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", className = "org.onvif.ver20.analytics.wsdl.GetRuleOptionsResponse")
    public Response<GetRuleOptionsResponse> getRuleOptionsAsync(
        @WebParam(name = "RuleType", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl")
        QName ruleType,
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl")
        String configurationToken);

    /**
     * 
     * 				Return the options for the supported rules that specify an Option attribute.
     * 			
     * 
     * @param ruleType
     * @param configurationToken
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetRuleOptions", action = "http://www.onvif.org/ver20/analytics/wsdl/GetRuleOptions")
    @RequestWrapper(localName = "GetRuleOptions", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", className = "org.onvif.ver20.analytics.wsdl.GetRuleOptions")
    @ResponseWrapper(localName = "GetRuleOptionsResponse", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", className = "org.onvif.ver20.analytics.wsdl.GetRuleOptionsResponse")
    public Future<?> getRuleOptionsAsync(
        @WebParam(name = "RuleType", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl")
        QName ruleType,
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl")
        String configurationToken,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetRuleOptionsResponse> asyncHandler);

    /**
     * 
     * 				Return the options for the supported rules that specify an Option attribute.
     * 			
     * 
     * @param ruleType
     * @param configurationToken
     * @return
     *     returns java.util.List<org.onvif.ver20.analytics.wsdl.ConfigOptions>
     */
    @WebMethod(operationName = "GetRuleOptions", action = "http://www.onvif.org/ver20/analytics/wsdl/GetRuleOptions")
    @WebResult(name = "RuleOptions", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl")
    @RequestWrapper(localName = "GetRuleOptions", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", className = "org.onvif.ver20.analytics.wsdl.GetRuleOptions")
    @ResponseWrapper(localName = "GetRuleOptionsResponse", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", className = "org.onvif.ver20.analytics.wsdl.GetRuleOptionsResponse")
    public List<ConfigOptions> getRuleOptions(
        @WebParam(name = "RuleType", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl")
        QName ruleType,
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl")
        String configurationToken);

    /**
     * 
     * 				Modify one or more rules of a VideoAnalyticsConfiguration. The rules are referenced by their names.
     * 			
     * 
     * @param rule
     * @param configurationToken
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver20.analytics.wsdl.ModifyRulesResponse>
     */
    @WebMethod(operationName = "ModifyRules", action = "http://www.onvif.org/ver20/analytics/wsdl/ModifyRules")
    @RequestWrapper(localName = "ModifyRules", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", className = "org.onvif.ver20.analytics.wsdl.ModifyRules")
    @ResponseWrapper(localName = "ModifyRulesResponse", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", className = "org.onvif.ver20.analytics.wsdl.ModifyRulesResponse")
    public Response<ModifyRulesResponse> modifyRulesAsync(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl")
        String configurationToken,
        @WebParam(name = "Rule", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl")
        List<Config> rule);

    /**
     * 
     * 				Modify one or more rules of a VideoAnalyticsConfiguration. The rules are referenced by their names.
     * 			
     * 
     * @param rule
     * @param configurationToken
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "ModifyRules", action = "http://www.onvif.org/ver20/analytics/wsdl/ModifyRules")
    @RequestWrapper(localName = "ModifyRules", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", className = "org.onvif.ver20.analytics.wsdl.ModifyRules")
    @ResponseWrapper(localName = "ModifyRulesResponse", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", className = "org.onvif.ver20.analytics.wsdl.ModifyRulesResponse")
    public Future<?> modifyRulesAsync(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl")
        String configurationToken,
        @WebParam(name = "Rule", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl")
        List<Config> rule,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<ModifyRulesResponse> asyncHandler);

    /**
     * 
     * 				Modify one or more rules of a VideoAnalyticsConfiguration. The rules are referenced by their names.
     * 			
     * 
     * @param rule
     * @param configurationToken
     */
    @WebMethod(operationName = "ModifyRules", action = "http://www.onvif.org/ver20/analytics/wsdl/ModifyRules")
    @RequestWrapper(localName = "ModifyRules", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", className = "org.onvif.ver20.analytics.wsdl.ModifyRules")
    @ResponseWrapper(localName = "ModifyRulesResponse", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", className = "org.onvif.ver20.analytics.wsdl.ModifyRulesResponse")
    public void modifyRules(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl")
        String configurationToken,
        @WebParam(name = "Rule", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl")
        List<Config> rule);

}
