
package org.onvif.ver20.analytics.wsdl;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RuleEngineService", targetNamespace = "http://www.onvif.org/ver20/analytics/wsdl", wsdlLocation = "classpath:wsdl/analyticsProxy.wsdl")
public class RuleEngineService
    extends Service
{

    private final static URL RULEENGINESERVICE_WSDL_LOCATION;
    private final static WebServiceException RULEENGINESERVICE_EXCEPTION;
    private final static QName RULEENGINESERVICE_QNAME = new QName("http://www.onvif.org/ver20/analytics/wsdl", "RuleEngineService");

    static {
        RULEENGINESERVICE_WSDL_LOCATION = org.onvif.ver20.analytics.wsdl.RuleEngineService.class.getResource("classpath:wsdl/analyticsProxy.wsdl");
        WebServiceException e = null;
        if (RULEENGINESERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'classpath:wsdl/analyticsProxy.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        RULEENGINESERVICE_EXCEPTION = e;
    }

    public RuleEngineService() {
        super(__getWsdlLocation(), RULEENGINESERVICE_QNAME);
    }

    public RuleEngineService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RULEENGINESERVICE_QNAME, features);
    }

    public RuleEngineService(URL wsdlLocation) {
        super(wsdlLocation, RULEENGINESERVICE_QNAME);
    }

    public RuleEngineService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RULEENGINESERVICE_QNAME, features);
    }

    public RuleEngineService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RuleEngineService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RuleEnginePort
     */
    @WebEndpoint(name = "RuleEngineServicePort")
    public RuleEnginePort getRuleEngineServicePort() {
        return super.getPort(new QName("http://www.onvif.org/ver20/analytics/wsdl", "RuleEngineServicePort"), RuleEnginePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RuleEnginePort
     */
    @WebEndpoint(name = "RuleEngineServicePort")
    public RuleEnginePort getRuleEngineServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.onvif.org/ver20/analytics/wsdl", "RuleEngineServicePort"), RuleEnginePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RULEENGINESERVICE_EXCEPTION!= null) {
            throw RULEENGINESERVICE_EXCEPTION;
        }
        return RULEENGINESERVICE_WSDL_LOCATION;
    }

}
