
package org.onvif.ver10.deviceio.wsdl;

import java.math.BigInteger;
import java.util.List;
import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.Duration;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;
import org.onvif.ver10.device.wsdl.GetRelayOutputsResponse;
import org.onvif.ver10.device.wsdl.SetRelayOutputStateResponse;
import org.onvif.ver10.schema.DigitalInput;
import org.onvif.ver10.schema.RelayLogicalState;
import org.onvif.ver10.schema.RelayOutput;
import org.onvif.ver10.schema.VideoOutput;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DeviceIOPort", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
@XmlSeeAlso({
    org.onvif.ver10.device.wsdl.ObjectFactory.class,
    org.oasis_open.docs.wsn.b_2.ObjectFactory.class,
    org.oasis_open.docs.wsn.t_1.ObjectFactory.class,
    org.oasis_open.docs.wsrf.bf_2.ObjectFactory.class,
    org.onvif.ver10.schema.ObjectFactory.class,
    org.onvif.ver10.deviceio.wsdl.ObjectFactory.class,
    org.w3._2003._05.soap_envelope.ObjectFactory.class,
    org.w3._2004._08.xop.include.ObjectFactory.class,
    org.w3._2005._05.xmlmime.ObjectFactory.class,
    org.w3._2005._08.addressing.ObjectFactory.class
})
public interface DeviceIOPort {


    /**
     * Returns the capabilities of the device IO service. The result is returned in a typed answer.
     * 
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver10.deviceio.wsdl.GetServiceCapabilitiesResponse>
     */
    @WebMethod(operationName = "GetServiceCapabilities", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetServiceCapabilities")
    @RequestWrapper(localName = "GetServiceCapabilities", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetServiceCapabilities")
    @ResponseWrapper(localName = "GetServiceCapabilitiesResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetServiceCapabilitiesResponse")
    public Response<GetServiceCapabilitiesResponse> getServiceCapabilitiesAsync();

    /**
     * Returns the capabilities of the device IO service. The result is returned in a typed answer.
     * 
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetServiceCapabilities", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetServiceCapabilities")
    @RequestWrapper(localName = "GetServiceCapabilities", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetServiceCapabilities")
    @ResponseWrapper(localName = "GetServiceCapabilitiesResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetServiceCapabilitiesResponse")
    public Future<?> getServiceCapabilitiesAsync(
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetServiceCapabilitiesResponse> asyncHandler);

    /**
     * Returns the capabilities of the device IO service. The result is returned in a typed answer.
     * 
     * @return
     *     returns org.onvif.ver10.deviceio.wsdl.Capabilities
     */
    @WebMethod(operationName = "GetServiceCapabilities", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetServiceCapabilities")
    @WebResult(name = "Capabilities", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
    @RequestWrapper(localName = "GetServiceCapabilities", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetServiceCapabilities")
    @ResponseWrapper(localName = "GetServiceCapabilitiesResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetServiceCapabilitiesResponse")
    public Capabilities getServiceCapabilities();

    /**
     * 
     * @param relayOutputToken
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver10.deviceio.wsdl.GetRelayOutputOptionsResponse>
     */
    @WebMethod(operationName = "GetRelayOutputOptions", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetRelayOutputOptions")
    @RequestWrapper(localName = "GetRelayOutputOptions", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetRelayOutputOptions")
    @ResponseWrapper(localName = "GetRelayOutputOptionsResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetRelayOutputOptionsResponse")
    public Response<GetRelayOutputOptionsResponse> getRelayOutputOptionsAsync(
        @WebParam(name = "RelayOutputToken", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        String relayOutputToken);

    /**
     * 
     * @param relayOutputToken
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetRelayOutputOptions", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetRelayOutputOptions")
    @RequestWrapper(localName = "GetRelayOutputOptions", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetRelayOutputOptions")
    @ResponseWrapper(localName = "GetRelayOutputOptionsResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetRelayOutputOptionsResponse")
    public Future<?> getRelayOutputOptionsAsync(
        @WebParam(name = "RelayOutputToken", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        String relayOutputToken,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetRelayOutputOptionsResponse> asyncHandler);

    /**
     * 
     * @param relayOutputToken
     * @return
     *     returns java.util.List<org.onvif.ver10.deviceio.wsdl.RelayOutputOptions>
     */
    @WebMethod(operationName = "GetRelayOutputOptions", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetRelayOutputOptions")
    @WebResult(name = "RelayOutputOptions", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
    @RequestWrapper(localName = "GetRelayOutputOptions", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetRelayOutputOptions")
    @ResponseWrapper(localName = "GetRelayOutputOptionsResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetRelayOutputOptionsResponse")
    public List<RelayOutputOptions> getRelayOutputOptions(
        @WebParam(name = "RelayOutputToken", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        String relayOutputToken);

    /**
     * List all available audio sources for the device. The device that has one or more audio sources shall support the listing of available audio inputs through the GetAudioSources command.
     * 
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver10.deviceio.wsdl.GetResponse>
     */
    @WebMethod(operationName = "GetAudioSources", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetAudioSources")
    @RequestWrapper(localName = "GetAudioSources", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.Get")
    @ResponseWrapper(localName = "GetAudioSourcesResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetResponse")
    public Response<GetResponse> getAudioSourcesAsync();

    /**
     * List all available audio sources for the device. The device that has one or more audio sources shall support the listing of available audio inputs through the GetAudioSources command.
     * 
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetAudioSources", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetAudioSources")
    @RequestWrapper(localName = "GetAudioSources", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.Get")
    @ResponseWrapper(localName = "GetAudioSourcesResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetResponse")
    public Future<?> getAudioSourcesAsync(
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetResponse> asyncHandler);

    /**
     * List all available audio sources for the device. The device that has one or more audio sources shall support the listing of available audio inputs through the GetAudioSources command.
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(operationName = "GetAudioSources", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetAudioSources")
    @WebResult(name = "Token", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
    @RequestWrapper(localName = "GetAudioSources", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.Get")
    @ResponseWrapper(localName = "GetAudioSourcesResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetResponse")
    public List<String> getAudioSources();

    /**
     * List all available audio outputs of a device. A device that has one ore more physical audio outputs shall support listing of available audio outputs through the GetAudioOutputs command.
     * 
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver10.deviceio.wsdl.GetResponse>
     */
    @WebMethod(operationName = "GetAudioOutputs", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetAudioOutputs")
    @RequestWrapper(localName = "GetAudioOutputs", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.Get")
    @ResponseWrapper(localName = "GetAudioOutputsResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetResponse")
    public Response<GetResponse> getAudioOutputsAsync();

    /**
     * List all available audio outputs of a device. A device that has one ore more physical audio outputs shall support listing of available audio outputs through the GetAudioOutputs command.
     * 
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetAudioOutputs", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetAudioOutputs")
    @RequestWrapper(localName = "GetAudioOutputs", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.Get")
    @ResponseWrapper(localName = "GetAudioOutputsResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetResponse")
    public Future<?> getAudioOutputsAsync(
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetResponse> asyncHandler);

    /**
     * List all available audio outputs of a device. A device that has one ore more physical audio outputs shall support listing of available audio outputs through the GetAudioOutputs command.
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(operationName = "GetAudioOutputs", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetAudioOutputs")
    @WebResult(name = "Token", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
    @RequestWrapper(localName = "GetAudioOutputs", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.Get")
    @ResponseWrapper(localName = "GetAudioOutputsResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetResponse")
    public List<String> getAudioOutputs();

    /**
     * List all available video sources for the device. The device that has one or more video inputs shall support the listing of available video sources through the GetVideoSources command.
     * 
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver10.deviceio.wsdl.GetResponse>
     */
    @WebMethod(operationName = "GetVideoSources", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetVideoSources")
    @RequestWrapper(localName = "GetVideoSources", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.Get")
    @ResponseWrapper(localName = "GetVideoSourcesResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetResponse")
    public Response<GetResponse> getVideoSourcesAsync();

    /**
     * List all available video sources for the device. The device that has one or more video inputs shall support the listing of available video sources through the GetVideoSources command.
     * 
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetVideoSources", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetVideoSources")
    @RequestWrapper(localName = "GetVideoSources", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.Get")
    @ResponseWrapper(localName = "GetVideoSourcesResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetResponse")
    public Future<?> getVideoSourcesAsync(
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetResponse> asyncHandler);

    /**
     * List all available video sources for the device. The device that has one or more video inputs shall support the listing of available video sources through the GetVideoSources command.
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(operationName = "GetVideoSources", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetVideoSources")
    @WebResult(name = "Token", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
    @RequestWrapper(localName = "GetVideoSources", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.Get")
    @ResponseWrapper(localName = "GetVideoSourcesResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetResponse")
    public List<String> getVideoSources();

    /**
     * List all available video outputs of a device. A device that has one or more physical video outputs shall support listing of available video outputs through the GetVideoOutputs command.
     * 
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver10.deviceio.wsdl.GetVideoOutputsResponse>
     */
    @WebMethod(operationName = "GetVideoOutputs", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetVideoOutputs")
    @RequestWrapper(localName = "GetVideoOutputs", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetVideoOutputs")
    @ResponseWrapper(localName = "GetVideoOutputsResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetVideoOutputsResponse")
    public Response<GetVideoOutputsResponse> getVideoOutputsAsync();

    /**
     * List all available video outputs of a device. A device that has one or more physical video outputs shall support listing of available video outputs through the GetVideoOutputs command.
     * 
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetVideoOutputs", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetVideoOutputs")
    @RequestWrapper(localName = "GetVideoOutputs", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetVideoOutputs")
    @ResponseWrapper(localName = "GetVideoOutputsResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetVideoOutputsResponse")
    public Future<?> getVideoOutputsAsync(
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetVideoOutputsResponse> asyncHandler);

    /**
     * List all available video outputs of a device. A device that has one or more physical video outputs shall support listing of available video outputs through the GetVideoOutputs command.
     * 
     * @return
     *     returns java.util.List<org.onvif.ver10.schema.VideoOutput>
     */
    @WebMethod(operationName = "GetVideoOutputs", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetVideoOutputs")
    @WebResult(name = "VideoOutputs", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
    @RequestWrapper(localName = "GetVideoOutputs", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetVideoOutputs")
    @ResponseWrapper(localName = "GetVideoOutputsResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetVideoOutputsResponse")
    public List<VideoOutput> getVideoOutputs();

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver10.deviceio.wsdl.GetVideoSourceConfigurationResponse>
     */
    @WebMethod(operationName = "GetVideoSourceConfiguration", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetVideoSourceConfiguration")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Response<GetVideoSourceConfigurationResponse> getVideoSourceConfigurationAsync(
        @WebParam(name = "GetVideoSourceConfiguration", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
        GetVideoSourceConfiguration parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetVideoSourceConfiguration", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetVideoSourceConfiguration")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Future<?> getVideoSourceConfigurationAsync(
        @WebParam(name = "GetVideoSourceConfiguration", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
        GetVideoSourceConfiguration parameters,
        @WebParam(name = "GetVideoSourceConfigurationResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetVideoSourceConfigurationResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.onvif.ver10.deviceio.wsdl.GetVideoSourceConfigurationResponse
     */
    @WebMethod(operationName = "GetVideoSourceConfiguration", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetVideoSourceConfiguration")
    @WebResult(name = "GetVideoSourceConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetVideoSourceConfigurationResponse getVideoSourceConfiguration(
        @WebParam(name = "GetVideoSourceConfiguration", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
        GetVideoSourceConfiguration parameters);

    /**
     * Get the configuration of a Video Output. A device that has one or more Video Outputs shall support the retrieval of the VideoOutputConfiguration through this command.
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver10.deviceio.wsdl.GetVideoOutputConfigurationResponse>
     */
    @WebMethod(operationName = "GetVideoOutputConfiguration", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetVideoOutputConfiguration")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Response<GetVideoOutputConfigurationResponse> getVideoOutputConfigurationAsync(
        @WebParam(name = "GetVideoOutputConfiguration", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
        GetVideoOutputConfiguration parameters);

    /**
     * Get the configuration of a Video Output. A device that has one or more Video Outputs shall support the retrieval of the VideoOutputConfiguration through this command.
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetVideoOutputConfiguration", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetVideoOutputConfiguration")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Future<?> getVideoOutputConfigurationAsync(
        @WebParam(name = "GetVideoOutputConfiguration", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
        GetVideoOutputConfiguration parameters,
        @WebParam(name = "GetVideoOutputConfigurationResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetVideoOutputConfigurationResponse> asyncHandler);

    /**
     * Get the configuration of a Video Output. A device that has one or more Video Outputs shall support the retrieval of the VideoOutputConfiguration through this command.
     * 
     * @param parameters
     * @return
     *     returns org.onvif.ver10.deviceio.wsdl.GetVideoOutputConfigurationResponse
     */
    @WebMethod(operationName = "GetVideoOutputConfiguration", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetVideoOutputConfiguration")
    @WebResult(name = "GetVideoOutputConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetVideoOutputConfigurationResponse getVideoOutputConfiguration(
        @WebParam(name = "GetVideoOutputConfiguration", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
        GetVideoOutputConfiguration parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver10.deviceio.wsdl.GetAudioSourceConfigurationResponse>
     */
    @WebMethod(operationName = "GetAudioSourceConfiguration", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetAudioSourceConfiguration")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Response<GetAudioSourceConfigurationResponse> getAudioSourceConfigurationAsync(
        @WebParam(name = "GetAudioSourceConfiguration", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
        GetAudioSourceConfiguration parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetAudioSourceConfiguration", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetAudioSourceConfiguration")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Future<?> getAudioSourceConfigurationAsync(
        @WebParam(name = "GetAudioSourceConfiguration", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
        GetAudioSourceConfiguration parameters,
        @WebParam(name = "GetAudioSourceConfigurationResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetAudioSourceConfigurationResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.onvif.ver10.deviceio.wsdl.GetAudioSourceConfigurationResponse
     */
    @WebMethod(operationName = "GetAudioSourceConfiguration", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetAudioSourceConfiguration")
    @WebResult(name = "GetAudioSourceConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetAudioSourceConfigurationResponse getAudioSourceConfiguration(
        @WebParam(name = "GetAudioSourceConfiguration", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
        GetAudioSourceConfiguration parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver10.deviceio.wsdl.GetAudioOutputConfigurationResponse>
     */
    @WebMethod(operationName = "GetAudioOutputConfiguration", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetAudioOutputConfiguration")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Response<GetAudioOutputConfigurationResponse> getAudioOutputConfigurationAsync(
        @WebParam(name = "GetAudioOutputConfiguration", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
        GetAudioOutputConfiguration parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetAudioOutputConfiguration", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetAudioOutputConfiguration")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Future<?> getAudioOutputConfigurationAsync(
        @WebParam(name = "GetAudioOutputConfiguration", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
        GetAudioOutputConfiguration parameters,
        @WebParam(name = "GetAudioOutputConfigurationResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetAudioOutputConfigurationResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.onvif.ver10.deviceio.wsdl.GetAudioOutputConfigurationResponse
     */
    @WebMethod(operationName = "GetAudioOutputConfiguration", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetAudioOutputConfiguration")
    @WebResult(name = "GetAudioOutputConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetAudioOutputConfigurationResponse getAudioOutputConfiguration(
        @WebParam(name = "GetAudioOutputConfiguration", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
        GetAudioOutputConfiguration parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver10.deviceio.wsdl.SetVideoSourceConfigurationResponse>
     */
    @WebMethod(operationName = "SetVideoSourceConfiguration", action = "http://www.onvif.org/ver10/deviceio/wsdl/SetVideoSourceConfiguration")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Response<SetVideoSourceConfigurationResponse> setVideoSourceConfigurationAsync(
        @WebParam(name = "SetVideoSourceConfiguration", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
        SetVideoSourceConfiguration parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "SetVideoSourceConfiguration", action = "http://www.onvif.org/ver10/deviceio/wsdl/SetVideoSourceConfiguration")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Future<?> setVideoSourceConfigurationAsync(
        @WebParam(name = "SetVideoSourceConfiguration", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
        SetVideoSourceConfiguration parameters,
        @WebParam(name = "SetVideoSourceConfigurationResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<SetVideoSourceConfigurationResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.onvif.ver10.deviceio.wsdl.SetVideoSourceConfigurationResponse
     */
    @WebMethod(operationName = "SetVideoSourceConfiguration", action = "http://www.onvif.org/ver10/deviceio/wsdl/SetVideoSourceConfiguration")
    @WebResult(name = "SetVideoSourceConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public SetVideoSourceConfigurationResponse setVideoSourceConfiguration(
        @WebParam(name = "SetVideoSourceConfiguration", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
        SetVideoSourceConfiguration parameters);

    /**
     * Modify a video output configuration. A device that has one or more video outputs shall support the setting of its video output configuration through this command.
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver10.deviceio.wsdl.SetVideoOutputConfigurationResponse>
     */
    @WebMethod(operationName = "SetVideoOutputConfiguration", action = "http://www.onvif.org/ver10/deviceio/wsdl/SetVideoOutputConfiguration")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Response<SetVideoOutputConfigurationResponse> setVideoOutputConfigurationAsync(
        @WebParam(name = "SetVideoOutputConfiguration", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
        SetVideoOutputConfiguration parameters);

    /**
     * Modify a video output configuration. A device that has one or more video outputs shall support the setting of its video output configuration through this command.
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "SetVideoOutputConfiguration", action = "http://www.onvif.org/ver10/deviceio/wsdl/SetVideoOutputConfiguration")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Future<?> setVideoOutputConfigurationAsync(
        @WebParam(name = "SetVideoOutputConfiguration", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
        SetVideoOutputConfiguration parameters,
        @WebParam(name = "SetVideoOutputConfigurationResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<SetVideoOutputConfigurationResponse> asyncHandler);

    /**
     * Modify a video output configuration. A device that has one or more video outputs shall support the setting of its video output configuration through this command.
     * 
     * @param parameters
     * @return
     *     returns org.onvif.ver10.deviceio.wsdl.SetVideoOutputConfigurationResponse
     */
    @WebMethod(operationName = "SetVideoOutputConfiguration", action = "http://www.onvif.org/ver10/deviceio/wsdl/SetVideoOutputConfiguration")
    @WebResult(name = "SetVideoOutputConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public SetVideoOutputConfigurationResponse setVideoOutputConfiguration(
        @WebParam(name = "SetVideoOutputConfiguration", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
        SetVideoOutputConfiguration parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver10.deviceio.wsdl.SetAudioSourceConfigurationResponse>
     */
    @WebMethod(operationName = "SetAudioSourceConfiguration", action = "http://www.onvif.org/ver10/deviceio/wsdl/SetAudioSourceConfiguration")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Response<SetAudioSourceConfigurationResponse> setAudioSourceConfigurationAsync(
        @WebParam(name = "SetAudioSourceConfiguration", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
        SetAudioSourceConfiguration parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "SetAudioSourceConfiguration", action = "http://www.onvif.org/ver10/deviceio/wsdl/SetAudioSourceConfiguration")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Future<?> setAudioSourceConfigurationAsync(
        @WebParam(name = "SetAudioSourceConfiguration", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
        SetAudioSourceConfiguration parameters,
        @WebParam(name = "SetAudioSourceConfigurationResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<SetAudioSourceConfigurationResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.onvif.ver10.deviceio.wsdl.SetAudioSourceConfigurationResponse
     */
    @WebMethod(operationName = "SetAudioSourceConfiguration", action = "http://www.onvif.org/ver10/deviceio/wsdl/SetAudioSourceConfiguration")
    @WebResult(name = "SetAudioSourceConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public SetAudioSourceConfigurationResponse setAudioSourceConfiguration(
        @WebParam(name = "SetAudioSourceConfiguration", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
        SetAudioSourceConfiguration parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver10.deviceio.wsdl.SetAudioOutputConfigurationResponse>
     */
    @WebMethod(operationName = "SetAudioOutputConfiguration", action = "http://www.onvif.org/ver10/deviceio/wsdl/SetAudioOutputConfiguration")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Response<SetAudioOutputConfigurationResponse> setAudioOutputConfigurationAsync(
        @WebParam(name = "SetAudioOutputConfiguration", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
        SetAudioOutputConfiguration parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "SetAudioOutputConfiguration", action = "http://www.onvif.org/ver10/deviceio/wsdl/SetAudioOutputConfiguration")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Future<?> setAudioOutputConfigurationAsync(
        @WebParam(name = "SetAudioOutputConfiguration", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
        SetAudioOutputConfiguration parameters,
        @WebParam(name = "SetAudioOutputConfigurationResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<SetAudioOutputConfigurationResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.onvif.ver10.deviceio.wsdl.SetAudioOutputConfigurationResponse
     */
    @WebMethod(operationName = "SetAudioOutputConfiguration", action = "http://www.onvif.org/ver10/deviceio/wsdl/SetAudioOutputConfiguration")
    @WebResult(name = "SetAudioOutputConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public SetAudioOutputConfigurationResponse setAudioOutputConfiguration(
        @WebParam(name = "SetAudioOutputConfiguration", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
        SetAudioOutputConfiguration parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver10.deviceio.wsdl.GetVideoSourceConfigurationOptionsResponse>
     */
    @WebMethod(operationName = "GetVideoSourceConfigurationOptions", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetVideoSourceConfigurationOptions")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Response<GetVideoSourceConfigurationOptionsResponse> getVideoSourceConfigurationOptionsAsync(
        @WebParam(name = "GetVideoSourceConfigurationOptions", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
        GetVideoSourceConfigurationOptions parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetVideoSourceConfigurationOptions", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetVideoSourceConfigurationOptions")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Future<?> getVideoSourceConfigurationOptionsAsync(
        @WebParam(name = "GetVideoSourceConfigurationOptions", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
        GetVideoSourceConfigurationOptions parameters,
        @WebParam(name = "GetVideoSourceConfigurationOptionsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetVideoSourceConfigurationOptionsResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.onvif.ver10.deviceio.wsdl.GetVideoSourceConfigurationOptionsResponse
     */
    @WebMethod(operationName = "GetVideoSourceConfigurationOptions", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetVideoSourceConfigurationOptions")
    @WebResult(name = "GetVideoSourceConfigurationOptionsResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetVideoSourceConfigurationOptionsResponse getVideoSourceConfigurationOptions(
        @WebParam(name = "GetVideoSourceConfigurationOptions", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
        GetVideoSourceConfigurationOptions parameters);

    /**
     * Request the VideoOutputConfigurationOptions of a VideoOutput. A device that has one or more video outputs shall support the retrieval of VideoOutputConfigurationOptions through this command.
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver10.deviceio.wsdl.GetVideoOutputConfigurationOptionsResponse>
     */
    @WebMethod(operationName = "GetVideoOutputConfigurationOptions", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetVideoOutputConfigurationOptions")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Response<GetVideoOutputConfigurationOptionsResponse> getVideoOutputConfigurationOptionsAsync(
        @WebParam(name = "GetVideoOutputConfigurationOptions", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
        GetVideoOutputConfigurationOptions parameters);

    /**
     * Request the VideoOutputConfigurationOptions of a VideoOutput. A device that has one or more video outputs shall support the retrieval of VideoOutputConfigurationOptions through this command.
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetVideoOutputConfigurationOptions", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetVideoOutputConfigurationOptions")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Future<?> getVideoOutputConfigurationOptionsAsync(
        @WebParam(name = "GetVideoOutputConfigurationOptions", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
        GetVideoOutputConfigurationOptions parameters,
        @WebParam(name = "GetVideoOutputConfigurationOptionsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetVideoOutputConfigurationOptionsResponse> asyncHandler);

    /**
     * Request the VideoOutputConfigurationOptions of a VideoOutput. A device that has one or more video outputs shall support the retrieval of VideoOutputConfigurationOptions through this command.
     * 
     * @param parameters
     * @return
     *     returns org.onvif.ver10.deviceio.wsdl.GetVideoOutputConfigurationOptionsResponse
     */
    @WebMethod(operationName = "GetVideoOutputConfigurationOptions", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetVideoOutputConfigurationOptions")
    @WebResult(name = "GetVideoOutputConfigurationOptionsResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetVideoOutputConfigurationOptionsResponse getVideoOutputConfigurationOptions(
        @WebParam(name = "GetVideoOutputConfigurationOptions", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
        GetVideoOutputConfigurationOptions parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver10.deviceio.wsdl.GetAudioSourceConfigurationOptionsResponse>
     */
    @WebMethod(operationName = "GetAudioSourceConfigurationOptions", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetAudioSourceConfigurationOptions")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Response<GetAudioSourceConfigurationOptionsResponse> getAudioSourceConfigurationOptionsAsync(
        @WebParam(name = "GetAudioSourceConfigurationOptions", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
        GetAudioSourceConfigurationOptions parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetAudioSourceConfigurationOptions", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetAudioSourceConfigurationOptions")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Future<?> getAudioSourceConfigurationOptionsAsync(
        @WebParam(name = "GetAudioSourceConfigurationOptions", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
        GetAudioSourceConfigurationOptions parameters,
        @WebParam(name = "GetAudioSourceConfigurationOptionsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetAudioSourceConfigurationOptionsResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.onvif.ver10.deviceio.wsdl.GetAudioSourceConfigurationOptionsResponse
     */
    @WebMethod(operationName = "GetAudioSourceConfigurationOptions", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetAudioSourceConfigurationOptions")
    @WebResult(name = "GetAudioSourceConfigurationOptionsResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetAudioSourceConfigurationOptionsResponse getAudioSourceConfigurationOptions(
        @WebParam(name = "GetAudioSourceConfigurationOptions", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
        GetAudioSourceConfigurationOptions parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver10.deviceio.wsdl.GetAudioOutputConfigurationOptionsResponse>
     */
    @WebMethod(operationName = "GetAudioOutputConfigurationOptions", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetAudioOutputConfigurationOptions")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Response<GetAudioOutputConfigurationOptionsResponse> getAudioOutputConfigurationOptionsAsync(
        @WebParam(name = "GetAudioOutputConfigurationOptions", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
        GetAudioOutputConfigurationOptions parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetAudioOutputConfigurationOptions", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetAudioOutputConfigurationOptions")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Future<?> getAudioOutputConfigurationOptionsAsync(
        @WebParam(name = "GetAudioOutputConfigurationOptions", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
        GetAudioOutputConfigurationOptions parameters,
        @WebParam(name = "GetAudioOutputConfigurationOptionsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetAudioOutputConfigurationOptionsResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.onvif.ver10.deviceio.wsdl.GetAudioOutputConfigurationOptionsResponse
     */
    @WebMethod(operationName = "GetAudioOutputConfigurationOptions", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetAudioOutputConfigurationOptions")
    @WebResult(name = "GetAudioOutputConfigurationOptionsResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetAudioOutputConfigurationOptionsResponse getAudioOutputConfigurationOptions(
        @WebParam(name = "GetAudioOutputConfigurationOptions", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", partName = "parameters")
        GetAudioOutputConfigurationOptions parameters);

    /**
     * This operation gets a list of all available relay outputs and their settings.
     * 
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver10.device.wsdl.GetRelayOutputsResponse>
     */
    @WebMethod(operationName = "GetRelayOutputs", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetRelayOutputs")
    @RequestWrapper(localName = "GetRelayOutputs", targetNamespace = "http://www.onvif.org/ver10/device/wsdl", className = "org.onvif.ver10.device.wsdl.GetRelayOutputs")
    @ResponseWrapper(localName = "GetRelayOutputsResponse", targetNamespace = "http://www.onvif.org/ver10/device/wsdl", className = "org.onvif.ver10.device.wsdl.GetRelayOutputsResponse")
    public Response<GetRelayOutputsResponse> getRelayOutputsAsync();

    /**
     * This operation gets a list of all available relay outputs and their settings.
     * 
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetRelayOutputs", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetRelayOutputs")
    @RequestWrapper(localName = "GetRelayOutputs", targetNamespace = "http://www.onvif.org/ver10/device/wsdl", className = "org.onvif.ver10.device.wsdl.GetRelayOutputs")
    @ResponseWrapper(localName = "GetRelayOutputsResponse", targetNamespace = "http://www.onvif.org/ver10/device/wsdl", className = "org.onvif.ver10.device.wsdl.GetRelayOutputsResponse")
    public Future<?> getRelayOutputsAsync(
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetRelayOutputsResponse> asyncHandler);

    /**
     * This operation gets a list of all available relay outputs and their settings.
     * 
     * @return
     *     returns java.util.List<org.onvif.ver10.schema.RelayOutput>
     */
    @WebMethod(operationName = "GetRelayOutputs", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetRelayOutputs")
    @WebResult(name = "RelayOutputs", targetNamespace = "http://www.onvif.org/ver10/device/wsdl")
    @RequestWrapper(localName = "GetRelayOutputs", targetNamespace = "http://www.onvif.org/ver10/device/wsdl", className = "org.onvif.ver10.device.wsdl.GetRelayOutputs")
    @ResponseWrapper(localName = "GetRelayOutputsResponse", targetNamespace = "http://www.onvif.org/ver10/device/wsdl", className = "org.onvif.ver10.device.wsdl.GetRelayOutputsResponse")
    public List<RelayOutput> getRelayOutputs();

    /**
     * 
     * @param relayOutput
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver10.deviceio.wsdl.SetRelayOutputSettingsResponse>
     */
    @WebMethod(operationName = "SetRelayOutputSettings", action = "http://www.onvif.org/ver10/deviceio/wsdl/SetRelayOutputSettings")
    @RequestWrapper(localName = "SetRelayOutputSettings", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.SetRelayOutputSettings")
    @ResponseWrapper(localName = "SetRelayOutputSettingsResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.SetRelayOutputSettingsResponse")
    public Response<SetRelayOutputSettingsResponse> setRelayOutputSettingsAsync(
        @WebParam(name = "RelayOutput", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        RelayOutput relayOutput);

    /**
     * 
     * @param relayOutput
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "SetRelayOutputSettings", action = "http://www.onvif.org/ver10/deviceio/wsdl/SetRelayOutputSettings")
    @RequestWrapper(localName = "SetRelayOutputSettings", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.SetRelayOutputSettings")
    @ResponseWrapper(localName = "SetRelayOutputSettingsResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.SetRelayOutputSettingsResponse")
    public Future<?> setRelayOutputSettingsAsync(
        @WebParam(name = "RelayOutput", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        RelayOutput relayOutput,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<SetRelayOutputSettingsResponse> asyncHandler);

    /**
     * 
     * @param relayOutput
     */
    @WebMethod(operationName = "SetRelayOutputSettings", action = "http://www.onvif.org/ver10/deviceio/wsdl/SetRelayOutputSettings")
    @RequestWrapper(localName = "SetRelayOutputSettings", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.SetRelayOutputSettings")
    @ResponseWrapper(localName = "SetRelayOutputSettingsResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.SetRelayOutputSettingsResponse")
    public void setRelayOutputSettings(
        @WebParam(name = "RelayOutput", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        RelayOutput relayOutput);

    /**
     * Modify the relay state.
     * 
     * @param relayOutputToken
     * @param logicalState
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver10.device.wsdl.SetRelayOutputStateResponse>
     */
    @WebMethod(operationName = "SetRelayOutputState", action = "http://www.onvif.org/ver10/deviceio/wsdl/SetRelayOutputState")
    @RequestWrapper(localName = "SetRelayOutputState", targetNamespace = "http://www.onvif.org/ver10/device/wsdl", className = "org.onvif.ver10.device.wsdl.SetRelayOutputState")
    @ResponseWrapper(localName = "SetRelayOutputStateResponse", targetNamespace = "http://www.onvif.org/ver10/device/wsdl", className = "org.onvif.ver10.device.wsdl.SetRelayOutputStateResponse")
    public Response<SetRelayOutputStateResponse> setRelayOutputStateAsync(
        @WebParam(name = "RelayOutputToken", targetNamespace = "http://www.onvif.org/ver10/device/wsdl")
        String relayOutputToken,
        @WebParam(name = "LogicalState", targetNamespace = "http://www.onvif.org/ver10/device/wsdl")
        RelayLogicalState logicalState);

    /**
     * Modify the relay state.
     * 
     * @param relayOutputToken
     * @param asyncHandler
     * @param logicalState
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "SetRelayOutputState", action = "http://www.onvif.org/ver10/deviceio/wsdl/SetRelayOutputState")
    @RequestWrapper(localName = "SetRelayOutputState", targetNamespace = "http://www.onvif.org/ver10/device/wsdl", className = "org.onvif.ver10.device.wsdl.SetRelayOutputState")
    @ResponseWrapper(localName = "SetRelayOutputStateResponse", targetNamespace = "http://www.onvif.org/ver10/device/wsdl", className = "org.onvif.ver10.device.wsdl.SetRelayOutputStateResponse")
    public Future<?> setRelayOutputStateAsync(
        @WebParam(name = "RelayOutputToken", targetNamespace = "http://www.onvif.org/ver10/device/wsdl")
        String relayOutputToken,
        @WebParam(name = "LogicalState", targetNamespace = "http://www.onvif.org/ver10/device/wsdl")
        RelayLogicalState logicalState,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<SetRelayOutputStateResponse> asyncHandler);

    /**
     * Modify the relay state.
     * 
     * @param relayOutputToken
     * @param logicalState
     */
    @WebMethod(operationName = "SetRelayOutputState", action = "http://www.onvif.org/ver10/deviceio/wsdl/SetRelayOutputState")
    @RequestWrapper(localName = "SetRelayOutputState", targetNamespace = "http://www.onvif.org/ver10/device/wsdl", className = "org.onvif.ver10.device.wsdl.SetRelayOutputState")
    @ResponseWrapper(localName = "SetRelayOutputStateResponse", targetNamespace = "http://www.onvif.org/ver10/device/wsdl", className = "org.onvif.ver10.device.wsdl.SetRelayOutputStateResponse")
    public void setRelayOutputState(
        @WebParam(name = "RelayOutputToken", targetNamespace = "http://www.onvif.org/ver10/device/wsdl")
        String relayOutputToken,
        @WebParam(name = "LogicalState", targetNamespace = "http://www.onvif.org/ver10/device/wsdl")
        RelayLogicalState logicalState);

    /**
     * This operation gets a list of all available digital inputs.
     * 
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver10.deviceio.wsdl.GetDigitalInputsResponse>
     */
    @WebMethod(operationName = "GetDigitalInputs", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetDigitalInputs")
    @RequestWrapper(localName = "GetDigitalInputs", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetDigitalInputs")
    @ResponseWrapper(localName = "GetDigitalInputsResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetDigitalInputsResponse")
    public Response<GetDigitalInputsResponse> getDigitalInputsAsync();

    /**
     * This operation gets a list of all available digital inputs.
     * 
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetDigitalInputs", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetDigitalInputs")
    @RequestWrapper(localName = "GetDigitalInputs", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetDigitalInputs")
    @ResponseWrapper(localName = "GetDigitalInputsResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetDigitalInputsResponse")
    public Future<?> getDigitalInputsAsync(
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetDigitalInputsResponse> asyncHandler);

    /**
     * This operation gets a list of all available digital inputs.
     * 
     * @return
     *     returns java.util.List<org.onvif.ver10.schema.DigitalInput>
     */
    @WebMethod(operationName = "GetDigitalInputs", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetDigitalInputs")
    @WebResult(name = "DigitalInputs", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
    @RequestWrapper(localName = "GetDigitalInputs", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetDigitalInputs")
    @ResponseWrapper(localName = "GetDigitalInputsResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetDigitalInputsResponse")
    public List<DigitalInput> getDigitalInputs();

    /**
     * This operation lists what configuration is available for digital inputs.
     * 
     * @param token
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver10.deviceio.wsdl.GetDigitalInputConfigurationOptionsResponse>
     */
    @WebMethod(operationName = "GetDigitalInputConfigurationOptions", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetDigitalInputConfigurationOptions")
    @RequestWrapper(localName = "GetDigitalInputConfigurationOptions", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetDigitalInputConfigurationOptions")
    @ResponseWrapper(localName = "GetDigitalInputConfigurationOptionsResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetDigitalInputConfigurationOptionsResponse")
    public Response<GetDigitalInputConfigurationOptionsResponse> getDigitalInputConfigurationOptionsAsync(
        @WebParam(name = "Token", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        String token);

    /**
     * This operation lists what configuration is available for digital inputs.
     * 
     * @param token
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetDigitalInputConfigurationOptions", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetDigitalInputConfigurationOptions")
    @RequestWrapper(localName = "GetDigitalInputConfigurationOptions", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetDigitalInputConfigurationOptions")
    @ResponseWrapper(localName = "GetDigitalInputConfigurationOptionsResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetDigitalInputConfigurationOptionsResponse")
    public Future<?> getDigitalInputConfigurationOptionsAsync(
        @WebParam(name = "Token", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        String token,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetDigitalInputConfigurationOptionsResponse> asyncHandler);

    /**
     * This operation lists what configuration is available for digital inputs.
     * 
     * @param token
     * @return
     *     returns org.onvif.ver10.deviceio.wsdl.DigitalInputConfigurationOptions
     */
    @WebMethod(operationName = "GetDigitalInputConfigurationOptions", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetDigitalInputConfigurationOptions")
    @WebResult(name = "DigitalInputOptions", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
    @RequestWrapper(localName = "GetDigitalInputConfigurationOptions", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetDigitalInputConfigurationOptions")
    @ResponseWrapper(localName = "GetDigitalInputConfigurationOptionsResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetDigitalInputConfigurationOptionsResponse")
    public DigitalInputConfigurationOptions getDigitalInputConfigurationOptions(
        @WebParam(name = "Token", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        String token);

    /**
     * Modify a digital input configuration.
     * 
     * @param digitalInputs
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver10.deviceio.wsdl.SetDigitalInputConfigurationsResponse>
     */
    @WebMethod(operationName = "SetDigitalInputConfigurations", action = "http://www.onvif.org/ver10/deviceio/wsdl/SetDigitalInputConfigurations")
    @RequestWrapper(localName = "SetDigitalInputConfigurations", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.SetDigitalInputConfigurations")
    @ResponseWrapper(localName = "SetDigitalInputConfigurationsResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.SetDigitalInputConfigurationsResponse")
    public Response<SetDigitalInputConfigurationsResponse> setDigitalInputConfigurationsAsync(
        @WebParam(name = "DigitalInputs", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        List<DigitalInput> digitalInputs);

    /**
     * Modify a digital input configuration.
     * 
     * @param asyncHandler
     * @param digitalInputs
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "SetDigitalInputConfigurations", action = "http://www.onvif.org/ver10/deviceio/wsdl/SetDigitalInputConfigurations")
    @RequestWrapper(localName = "SetDigitalInputConfigurations", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.SetDigitalInputConfigurations")
    @ResponseWrapper(localName = "SetDigitalInputConfigurationsResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.SetDigitalInputConfigurationsResponse")
    public Future<?> setDigitalInputConfigurationsAsync(
        @WebParam(name = "DigitalInputs", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        List<DigitalInput> digitalInputs,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<SetDigitalInputConfigurationsResponse> asyncHandler);

    /**
     * Modify a digital input configuration.
     * 
     * @param digitalInputs
     */
    @WebMethod(operationName = "SetDigitalInputConfigurations", action = "http://www.onvif.org/ver10/deviceio/wsdl/SetDigitalInputConfigurations")
    @RequestWrapper(localName = "SetDigitalInputConfigurations", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.SetDigitalInputConfigurations")
    @ResponseWrapper(localName = "SetDigitalInputConfigurationsResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.SetDigitalInputConfigurationsResponse")
    public void setDigitalInputConfigurations(
        @WebParam(name = "DigitalInputs", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        List<DigitalInput> digitalInputs);

    /**
     * 
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver10.deviceio.wsdl.GetSerialPortsResponse>
     */
    @WebMethod(operationName = "GetSerialPorts", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetSerialPorts")
    @RequestWrapper(localName = "GetSerialPorts", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetSerialPorts")
    @ResponseWrapper(localName = "GetSerialPortsResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetSerialPortsResponse")
    public Response<GetSerialPortsResponse> getSerialPortsAsync();

    /**
     * 
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetSerialPorts", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetSerialPorts")
    @RequestWrapper(localName = "GetSerialPorts", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetSerialPorts")
    @ResponseWrapper(localName = "GetSerialPortsResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetSerialPortsResponse")
    public Future<?> getSerialPortsAsync(
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetSerialPortsResponse> asyncHandler);

    /**
     * 
     * @return
     *     returns java.util.List<org.onvif.ver10.deviceio.wsdl.SerialPort>
     */
    @WebMethod(operationName = "GetSerialPorts", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetSerialPorts")
    @WebResult(name = "SerialPort", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
    @RequestWrapper(localName = "GetSerialPorts", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetSerialPorts")
    @ResponseWrapper(localName = "GetSerialPortsResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetSerialPortsResponse")
    public List<SerialPort> getSerialPorts();

    /**
     * 
     * @param serialPortToken
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver10.deviceio.wsdl.GetSerialPortConfigurationResponse>
     */
    @WebMethod(operationName = "GetSerialPortConfiguration", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetSerialPortConfigurations")
    @RequestWrapper(localName = "GetSerialPortConfiguration", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetSerialPortConfiguration")
    @ResponseWrapper(localName = "GetSerialPortConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetSerialPortConfigurationResponse")
    public Response<GetSerialPortConfigurationResponse> getSerialPortConfigurationAsync(
        @WebParam(name = "SerialPortToken", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        String serialPortToken);

    /**
     * 
     * @param serialPortToken
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetSerialPortConfiguration", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetSerialPortConfigurations")
    @RequestWrapper(localName = "GetSerialPortConfiguration", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetSerialPortConfiguration")
    @ResponseWrapper(localName = "GetSerialPortConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetSerialPortConfigurationResponse")
    public Future<?> getSerialPortConfigurationAsync(
        @WebParam(name = "SerialPortToken", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        String serialPortToken,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetSerialPortConfigurationResponse> asyncHandler);

    /**
     * 
     * @param serialPortToken
     * @return
     *     returns org.onvif.ver10.deviceio.wsdl.SerialPortConfiguration
     */
    @WebMethod(operationName = "GetSerialPortConfiguration", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetSerialPortConfigurations")
    @WebResult(name = "SerialPortConfiguration", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
    @RequestWrapper(localName = "GetSerialPortConfiguration", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetSerialPortConfiguration")
    @ResponseWrapper(localName = "GetSerialPortConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetSerialPortConfigurationResponse")
    public SerialPortConfiguration getSerialPortConfiguration(
        @WebParam(name = "SerialPortToken", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        String serialPortToken);

    /**
     * 
     * @param forcePersistance
     * @param serialPortConfiguration
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver10.deviceio.wsdl.SetSerialPortConfigurationResponse>
     */
    @WebMethod(operationName = "SetSerialPortConfiguration", action = "http://www.onvif.org/ver10/deviceio/wsdl/SetSerialPortConfiguration")
    @RequestWrapper(localName = "SetSerialPortConfiguration", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.SetSerialPortConfiguration")
    @ResponseWrapper(localName = "SetSerialPortConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.SetSerialPortConfigurationResponse")
    public Response<SetSerialPortConfigurationResponse> setSerialPortConfigurationAsync(
        @WebParam(name = "SerialPortConfiguration", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        SerialPortConfiguration serialPortConfiguration,
        @WebParam(name = "ForcePersistance", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        boolean forcePersistance);

    /**
     * 
     * @param asyncHandler
     * @param forcePersistance
     * @param serialPortConfiguration
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "SetSerialPortConfiguration", action = "http://www.onvif.org/ver10/deviceio/wsdl/SetSerialPortConfiguration")
    @RequestWrapper(localName = "SetSerialPortConfiguration", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.SetSerialPortConfiguration")
    @ResponseWrapper(localName = "SetSerialPortConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.SetSerialPortConfigurationResponse")
    public Future<?> setSerialPortConfigurationAsync(
        @WebParam(name = "SerialPortConfiguration", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        SerialPortConfiguration serialPortConfiguration,
        @WebParam(name = "ForcePersistance", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        boolean forcePersistance,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<SetSerialPortConfigurationResponse> asyncHandler);

    /**
     * 
     * @param forcePersistance
     * @param serialPortConfiguration
     */
    @WebMethod(operationName = "SetSerialPortConfiguration", action = "http://www.onvif.org/ver10/deviceio/wsdl/SetSerialPortConfiguration")
    @RequestWrapper(localName = "SetSerialPortConfiguration", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.SetSerialPortConfiguration")
    @ResponseWrapper(localName = "SetSerialPortConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.SetSerialPortConfigurationResponse")
    public void setSerialPortConfiguration(
        @WebParam(name = "SerialPortConfiguration", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        SerialPortConfiguration serialPortConfiguration,
        @WebParam(name = "ForcePersistance", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        boolean forcePersistance);

    /**
     * 
     * @param serialPortToken
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver10.deviceio.wsdl.GetSerialPortConfigurationOptionsResponse>
     */
    @WebMethod(operationName = "GetSerialPortConfigurationOptions", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetSerialPortConfigurationOptions")
    @RequestWrapper(localName = "GetSerialPortConfigurationOptions", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetSerialPortConfigurationOptions")
    @ResponseWrapper(localName = "GetSerialPortConfigurationOptionsResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetSerialPortConfigurationOptionsResponse")
    public Response<GetSerialPortConfigurationOptionsResponse> getSerialPortConfigurationOptionsAsync(
        @WebParam(name = "SerialPortToken", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        String serialPortToken);

    /**
     * 
     * @param serialPortToken
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetSerialPortConfigurationOptions", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetSerialPortConfigurationOptions")
    @RequestWrapper(localName = "GetSerialPortConfigurationOptions", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetSerialPortConfigurationOptions")
    @ResponseWrapper(localName = "GetSerialPortConfigurationOptionsResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetSerialPortConfigurationOptionsResponse")
    public Future<?> getSerialPortConfigurationOptionsAsync(
        @WebParam(name = "SerialPortToken", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        String serialPortToken,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetSerialPortConfigurationOptionsResponse> asyncHandler);

    /**
     * 
     * @param serialPortToken
     * @return
     *     returns org.onvif.ver10.deviceio.wsdl.SerialPortConfigurationOptions
     */
    @WebMethod(operationName = "GetSerialPortConfigurationOptions", action = "http://www.onvif.org/ver10/deviceio/wsdl/GetSerialPortConfigurationOptions")
    @WebResult(name = "SerialPortOptions", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
    @RequestWrapper(localName = "GetSerialPortConfigurationOptions", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetSerialPortConfigurationOptions")
    @ResponseWrapper(localName = "GetSerialPortConfigurationOptionsResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.GetSerialPortConfigurationOptionsResponse")
    public SerialPortConfigurationOptions getSerialPortConfigurationOptions(
        @WebParam(name = "SerialPortToken", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        String serialPortToken);

    /**
     * 
     * @param delimiter
     * @param timeOut
     * @param token
     * @param dataLength
     * @param serialData
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver10.deviceio.wsdl.SendReceiveSerialCommandResponse>
     */
    @WebMethod(operationName = "SendReceiveSerialCommand", action = "http://www.onvif.org/ver10/deviceio/wsdl/SendReceiveSerialCommand")
    @RequestWrapper(localName = "SendReceiveSerialCommand", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.SendReceiveSerialCommand")
    @ResponseWrapper(localName = "SendReceiveSerialCommandResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.SendReceiveSerialCommandResponse")
    public Response<SendReceiveSerialCommandResponse> sendReceiveSerialCommandAsync(
        @WebParam(name = "Token", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        String token,
        @WebParam(name = "SerialData", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        SerialData serialData,
        @WebParam(name = "TimeOut", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        Duration timeOut,
        @WebParam(name = "DataLength", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        BigInteger dataLength,
        @WebParam(name = "Delimiter", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        String delimiter);

    /**
     * 
     * @param delimiter
     * @param timeOut
     * @param token
     * @param asyncHandler
     * @param dataLength
     * @param serialData
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "SendReceiveSerialCommand", action = "http://www.onvif.org/ver10/deviceio/wsdl/SendReceiveSerialCommand")
    @RequestWrapper(localName = "SendReceiveSerialCommand", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.SendReceiveSerialCommand")
    @ResponseWrapper(localName = "SendReceiveSerialCommandResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.SendReceiveSerialCommandResponse")
    public Future<?> sendReceiveSerialCommandAsync(
        @WebParam(name = "Token", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        String token,
        @WebParam(name = "SerialData", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        SerialData serialData,
        @WebParam(name = "TimeOut", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        Duration timeOut,
        @WebParam(name = "DataLength", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        BigInteger dataLength,
        @WebParam(name = "Delimiter", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        String delimiter,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<SendReceiveSerialCommandResponse> asyncHandler);

    /**
     * 
     * @param delimiter
     * @param timeOut
     * @param token
     * @param dataLength
     * @param serialData
     */
    @WebMethod(operationName = "SendReceiveSerialCommand", action = "http://www.onvif.org/ver10/deviceio/wsdl/SendReceiveSerialCommand")
    @RequestWrapper(localName = "SendReceiveSerialCommand", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.SendReceiveSerialCommand")
    @ResponseWrapper(localName = "SendReceiveSerialCommandResponse", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", className = "org.onvif.ver10.deviceio.wsdl.SendReceiveSerialCommandResponse")
    public void sendReceiveSerialCommand(
        @WebParam(name = "Token", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        String token,
        @WebParam(name = "SerialData", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", mode = WebParam.Mode.INOUT)
        Holder<SerialData> serialData,
        @WebParam(name = "TimeOut", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        Duration timeOut,
        @WebParam(name = "DataLength", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        BigInteger dataLength,
        @WebParam(name = "Delimiter", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl")
        String delimiter);

}
