
package org.onvif.ver10.deviceio.wsdl;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DeviceIOService", targetNamespace = "http://www.onvif.org/ver10/deviceIO/wsdl", wsdlLocation = "classpath:wsdl/deviceioProxy.wsdl")
public class DeviceIOService
    extends Service
{

    private final static URL DEVICEIOSERVICE_WSDL_LOCATION;
    private final static WebServiceException DEVICEIOSERVICE_EXCEPTION;
    private final static QName DEVICEIOSERVICE_QNAME = new QName("http://www.onvif.org/ver10/deviceIO/wsdl", "DeviceIOService");

    static {
        DEVICEIOSERVICE_WSDL_LOCATION = org.onvif.ver10.deviceio.wsdl.DeviceIOService.class.getResource("classpath:wsdl/deviceioProxy.wsdl");
        WebServiceException e = null;
        if (DEVICEIOSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'classpath:wsdl/deviceioProxy.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        DEVICEIOSERVICE_EXCEPTION = e;
    }

    public DeviceIOService() {
        super(__getWsdlLocation(), DEVICEIOSERVICE_QNAME);
    }

    public DeviceIOService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DEVICEIOSERVICE_QNAME, features);
    }

    public DeviceIOService(URL wsdlLocation) {
        super(wsdlLocation, DEVICEIOSERVICE_QNAME);
    }

    public DeviceIOService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DEVICEIOSERVICE_QNAME, features);
    }

    public DeviceIOService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeviceIOService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DeviceIOPort
     */
    @WebEndpoint(name = "DeviceIOServicePort")
    public DeviceIOPort getDeviceIOServicePort() {
        return super.getPort(new QName("http://www.onvif.org/ver10/deviceIO/wsdl", "DeviceIOServicePort"), DeviceIOPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeviceIOPort
     */
    @WebEndpoint(name = "DeviceIOServicePort")
    public DeviceIOPort getDeviceIOServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.onvif.org/ver10/deviceIO/wsdl", "DeviceIOServicePort"), DeviceIOPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DEVICEIOSERVICE_EXCEPTION!= null) {
            throw DEVICEIOSERVICE_EXCEPTION;
        }
        return DEVICEIOSERVICE_WSDL_LOCATION;
    }

}
