
package org.onvif.ver20.imaging.wsdl;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ImagingService", targetNamespace = "http://www.onvif.org/ver20/imaging/wsdl", wsdlLocation = "classpath:wsdl/imagingProxy.wsdl")
public class ImagingService
    extends Service
{

    private final static URL IMAGINGSERVICE_WSDL_LOCATION;
    private final static WebServiceException IMAGINGSERVICE_EXCEPTION;
    private final static QName IMAGINGSERVICE_QNAME = new QName("http://www.onvif.org/ver20/imaging/wsdl", "ImagingService");

    static {
        IMAGINGSERVICE_WSDL_LOCATION = org.onvif.ver20.imaging.wsdl.ImagingService.class.getResource("classpath:wsdl/imagingProxy.wsdl");
        WebServiceException e = null;
        if (IMAGINGSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'classpath:wsdl/imagingProxy.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        IMAGINGSERVICE_EXCEPTION = e;
    }

    public ImagingService() {
        super(__getWsdlLocation(), IMAGINGSERVICE_QNAME);
    }

    public ImagingService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IMAGINGSERVICE_QNAME, features);
    }

    public ImagingService(URL wsdlLocation) {
        super(wsdlLocation, IMAGINGSERVICE_QNAME);
    }

    public ImagingService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IMAGINGSERVICE_QNAME, features);
    }

    public ImagingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ImagingService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ImagingPort
     */
    @WebEndpoint(name = "ImagingServicePort")
    public ImagingPort getImagingServicePort() {
        return super.getPort(new QName("http://www.onvif.org/ver20/imaging/wsdl", "ImagingServicePort"), ImagingPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ImagingPort
     */
    @WebEndpoint(name = "ImagingServicePort")
    public ImagingPort getImagingServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.onvif.org/ver20/imaging/wsdl", "ImagingServicePort"), ImagingPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IMAGINGSERVICE_EXCEPTION!= null) {
            throw IMAGINGSERVICE_EXCEPTION;
        }
        return IMAGINGSERVICE_WSDL_LOCATION;
    }

}
