
package org.onvif.ver20.ptz.wsdl;

import java.util.List;
import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.Duration;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;
import org.onvif.ver10.schema.GeoLocation;
import org.onvif.ver10.schema.PTZConfiguration;
import org.onvif.ver10.schema.PTZConfigurationOptions;
import org.onvif.ver10.schema.PTZNode;
import org.onvif.ver10.schema.PTZPreset;
import org.onvif.ver10.schema.PTZPresetTourOperation;
import org.onvif.ver10.schema.PTZPresetTourOptions;
import org.onvif.ver10.schema.PTZSpeed;
import org.onvif.ver10.schema.PTZStatus;
import org.onvif.ver10.schema.PTZVector;
import org.onvif.ver10.schema.PresetTour;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PTZ", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
@XmlSeeAlso({
    org.oasis_open.docs.wsn.b_2.ObjectFactory.class,
    org.oasis_open.docs.wsn.t_1.ObjectFactory.class,
    org.oasis_open.docs.wsrf.bf_2.ObjectFactory.class,
    org.onvif.ver10.schema.ObjectFactory.class,
    org.onvif.ver20.ptz.wsdl.ObjectFactory.class,
    org.w3._2003._05.soap_envelope.ObjectFactory.class,
    org.w3._2004._08.xop.include.ObjectFactory.class,
    org.w3._2005._05.xmlmime.ObjectFactory.class,
    org.w3._2005._08.addressing.ObjectFactory.class
})
public interface PTZ {


    /**
     * Returns the capabilities of the PTZ service. The result is returned in a typed answer.
     * 
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver20.ptz.wsdl.GetServiceCapabilitiesResponse>
     */
    @WebMethod(operationName = "GetServiceCapabilities", action = "http://www.onvif.org/ver20/ptz/wsdl/GetServiceCapabilities")
    @RequestWrapper(localName = "GetServiceCapabilities", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetServiceCapabilities")
    @ResponseWrapper(localName = "GetServiceCapabilitiesResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetServiceCapabilitiesResponse")
    public Response<GetServiceCapabilitiesResponse> getServiceCapabilitiesAsync();

    /**
     * Returns the capabilities of the PTZ service. The result is returned in a typed answer.
     * 
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetServiceCapabilities", action = "http://www.onvif.org/ver20/ptz/wsdl/GetServiceCapabilities")
    @RequestWrapper(localName = "GetServiceCapabilities", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetServiceCapabilities")
    @ResponseWrapper(localName = "GetServiceCapabilitiesResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetServiceCapabilitiesResponse")
    public Future<?> getServiceCapabilitiesAsync(
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetServiceCapabilitiesResponse> asyncHandler);

    /**
     * Returns the capabilities of the PTZ service. The result is returned in a typed answer.
     * 
     * @return
     *     returns org.onvif.ver20.ptz.wsdl.Capabilities
     */
    @WebMethod(operationName = "GetServiceCapabilities", action = "http://www.onvif.org/ver20/ptz/wsdl/GetServiceCapabilities")
    @WebResult(name = "Capabilities", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
    @RequestWrapper(localName = "GetServiceCapabilities", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetServiceCapabilities")
    @ResponseWrapper(localName = "GetServiceCapabilitiesResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetServiceCapabilitiesResponse")
    public Capabilities getServiceCapabilities();

    /**
     * 
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver20.ptz.wsdl.GetConfigurationsResponse>
     */
    @WebMethod(operationName = "GetConfigurations", action = "http://www.onvif.org/ver20/ptz/wsdl/GetConfigurations")
    @RequestWrapper(localName = "GetConfigurations", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetConfigurations")
    @ResponseWrapper(localName = "GetConfigurationsResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetConfigurationsResponse")
    public Response<GetConfigurationsResponse> getConfigurationsAsync();

    /**
     * 
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetConfigurations", action = "http://www.onvif.org/ver20/ptz/wsdl/GetConfigurations")
    @RequestWrapper(localName = "GetConfigurations", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetConfigurations")
    @ResponseWrapper(localName = "GetConfigurationsResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetConfigurationsResponse")
    public Future<?> getConfigurationsAsync(
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetConfigurationsResponse> asyncHandler);

    /**
     * 
     * @return
     *     returns java.util.List<org.onvif.ver10.schema.PTZConfiguration>
     */
    @WebMethod(operationName = "GetConfigurations", action = "http://www.onvif.org/ver20/ptz/wsdl/GetConfigurations")
    @WebResult(name = "PTZConfiguration", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
    @RequestWrapper(localName = "GetConfigurations", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetConfigurations")
    @ResponseWrapper(localName = "GetConfigurationsResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetConfigurationsResponse")
    public List<PTZConfiguration> getConfigurations();

    /**
     * 
     *         Operation to request all PTZ presets for the PTZNode
     *         in the selected profile. The operation is supported if there is support
     *         for at least on PTZ preset by the PTZNode.
     * 
     * @param profileToken
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver20.ptz.wsdl.GetPresetsResponse>
     */
    @WebMethod(operationName = "GetPresets", action = "http://www.onvif.org/ver20/ptz/wsdl/GetPresets")
    @RequestWrapper(localName = "GetPresets", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetPresets")
    @ResponseWrapper(localName = "GetPresetsResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetPresetsResponse")
    public Response<GetPresetsResponse> getPresetsAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken);

    /**
     * 
     *         Operation to request all PTZ presets for the PTZNode
     *         in the selected profile. The operation is supported if there is support
     *         for at least on PTZ preset by the PTZNode.
     * 
     * @param asyncHandler
     * @param profileToken
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetPresets", action = "http://www.onvif.org/ver20/ptz/wsdl/GetPresets")
    @RequestWrapper(localName = "GetPresets", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetPresets")
    @ResponseWrapper(localName = "GetPresetsResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetPresetsResponse")
    public Future<?> getPresetsAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetPresetsResponse> asyncHandler);

    /**
     * 
     *         Operation to request all PTZ presets for the PTZNode
     *         in the selected profile. The operation is supported if there is support
     *         for at least on PTZ preset by the PTZNode.
     * 
     * @param profileToken
     * @return
     *     returns java.util.List<org.onvif.ver10.schema.PTZPreset>
     */
    @WebMethod(operationName = "GetPresets", action = "http://www.onvif.org/ver20/ptz/wsdl/GetPresets")
    @WebResult(name = "Preset", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
    @RequestWrapper(localName = "GetPresets", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetPresets")
    @ResponseWrapper(localName = "GetPresetsResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetPresetsResponse")
    public List<PTZPreset> getPresets(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken);

    /**
     * 
     * 				The SetPreset command saves the current device position parameters so that the device can
     * 				move to the saved preset position through the GotoPreset operation.
     * 				In order to create a new preset, the SetPresetRequest contains no PresetToken. If creation is
     * 				successful, the Response contains the PresetToken which uniquely identifies the Preset. An
     * 				existing Preset can be overwritten by specifying the PresetToken of the corresponding Preset.
     * 				In both cases (overwriting or creation) an optional PresetName can be specified. The
     * 				operation fails if the PTZ device is moving during the SetPreset operation.
     * 				The device MAY internally save additional states such as imaging properties in the PTZ
     * 				Preset which then should be recalled in the GotoPreset operation.      
     * 
     * @param presetToken
     * @param presetName
     * @param profileToken
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver20.ptz.wsdl.SetPresetResponse>
     */
    @WebMethod(operationName = "SetPreset", action = "http://www.onvif.org/ver20/ptz/wsdl/SetPreset")
    @RequestWrapper(localName = "SetPreset", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.SetPreset")
    @ResponseWrapper(localName = "SetPresetResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.SetPresetResponse")
    public Response<SetPresetResponse> setPresetAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "PresetName", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String presetName,
        @WebParam(name = "PresetToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String presetToken);

    /**
     * 
     * 				The SetPreset command saves the current device position parameters so that the device can
     * 				move to the saved preset position through the GotoPreset operation.
     * 				In order to create a new preset, the SetPresetRequest contains no PresetToken. If creation is
     * 				successful, the Response contains the PresetToken which uniquely identifies the Preset. An
     * 				existing Preset can be overwritten by specifying the PresetToken of the corresponding Preset.
     * 				In both cases (overwriting or creation) an optional PresetName can be specified. The
     * 				operation fails if the PTZ device is moving during the SetPreset operation.
     * 				The device MAY internally save additional states such as imaging properties in the PTZ
     * 				Preset which then should be recalled in the GotoPreset operation.      
     * 
     * @param presetToken
     * @param asyncHandler
     * @param presetName
     * @param profileToken
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "SetPreset", action = "http://www.onvif.org/ver20/ptz/wsdl/SetPreset")
    @RequestWrapper(localName = "SetPreset", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.SetPreset")
    @ResponseWrapper(localName = "SetPresetResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.SetPresetResponse")
    public Future<?> setPresetAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "PresetName", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String presetName,
        @WebParam(name = "PresetToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String presetToken,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<SetPresetResponse> asyncHandler);

    /**
     * 
     * 				The SetPreset command saves the current device position parameters so that the device can
     * 				move to the saved preset position through the GotoPreset operation.
     * 				In order to create a new preset, the SetPresetRequest contains no PresetToken. If creation is
     * 				successful, the Response contains the PresetToken which uniquely identifies the Preset. An
     * 				existing Preset can be overwritten by specifying the PresetToken of the corresponding Preset.
     * 				In both cases (overwriting or creation) an optional PresetName can be specified. The
     * 				operation fails if the PTZ device is moving during the SetPreset operation.
     * 				The device MAY internally save additional states such as imaging properties in the PTZ
     * 				Preset which then should be recalled in the GotoPreset operation.      
     * 
     * @param presetToken
     * @param presetName
     * @param profileToken
     */
    @WebMethod(operationName = "SetPreset", action = "http://www.onvif.org/ver20/ptz/wsdl/SetPreset")
    @RequestWrapper(localName = "SetPreset", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.SetPreset")
    @ResponseWrapper(localName = "SetPresetResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.SetPresetResponse")
    public void setPreset(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "PresetName", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String presetName,
        @WebParam(name = "PresetToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", mode = WebParam.Mode.INOUT)
        Holder<String> presetToken);

    /**
     * 
     *         Operation to remove a PTZ preset for the Node in
     *         the
     *         selected profile. The operation is supported if the
     *         PresetPosition
     *         capability exists for teh Node in the
     *         selected profile.
     *       
     * 
     * @param presetToken
     * @param profileToken
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver20.ptz.wsdl.RemovePresetResponse>
     */
    @WebMethod(operationName = "RemovePreset", action = "http://www.onvif.org/ver20/ptz/wsdl/RemovePreset")
    @RequestWrapper(localName = "RemovePreset", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.RemovePreset")
    @ResponseWrapper(localName = "RemovePresetResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.RemovePresetResponse")
    public Response<RemovePresetResponse> removePresetAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "PresetToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String presetToken);

    /**
     * 
     *         Operation to remove a PTZ preset for the Node in
     *         the
     *         selected profile. The operation is supported if the
     *         PresetPosition
     *         capability exists for teh Node in the
     *         selected profile.
     *       
     * 
     * @param presetToken
     * @param asyncHandler
     * @param profileToken
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "RemovePreset", action = "http://www.onvif.org/ver20/ptz/wsdl/RemovePreset")
    @RequestWrapper(localName = "RemovePreset", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.RemovePreset")
    @ResponseWrapper(localName = "RemovePresetResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.RemovePresetResponse")
    public Future<?> removePresetAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "PresetToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String presetToken,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<RemovePresetResponse> asyncHandler);

    /**
     * 
     *         Operation to remove a PTZ preset for the Node in
     *         the
     *         selected profile. The operation is supported if the
     *         PresetPosition
     *         capability exists for teh Node in the
     *         selected profile.
     *       
     * 
     * @param presetToken
     * @param profileToken
     */
    @WebMethod(operationName = "RemovePreset", action = "http://www.onvif.org/ver20/ptz/wsdl/RemovePreset")
    @RequestWrapper(localName = "RemovePreset", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.RemovePreset")
    @ResponseWrapper(localName = "RemovePresetResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.RemovePresetResponse")
    public void removePreset(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "PresetToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String presetToken);

    /**
     * 
     *         Operation to go to a saved preset position for the
     *         PTZNode in the selected profile. The operation is supported if there is
     *         support for at least on PTZ preset by the PTZNode.
     * 
     * @param presetToken
     * @param speed
     * @param profileToken
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver20.ptz.wsdl.GotoPresetResponse>
     */
    @WebMethod(operationName = "GotoPreset", action = "http://www.onvif.org/ver20/ptz/wsdl/GotoPreset")
    @RequestWrapper(localName = "GotoPreset", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GotoPreset")
    @ResponseWrapper(localName = "GotoPresetResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GotoPresetResponse")
    public Response<GotoPresetResponse> gotoPresetAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "PresetToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String presetToken,
        @WebParam(name = "Speed", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        PTZSpeed speed);

    /**
     * 
     *         Operation to go to a saved preset position for the
     *         PTZNode in the selected profile. The operation is supported if there is
     *         support for at least on PTZ preset by the PTZNode.
     * 
     * @param presetToken
     * @param speed
     * @param asyncHandler
     * @param profileToken
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GotoPreset", action = "http://www.onvif.org/ver20/ptz/wsdl/GotoPreset")
    @RequestWrapper(localName = "GotoPreset", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GotoPreset")
    @ResponseWrapper(localName = "GotoPresetResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GotoPresetResponse")
    public Future<?> gotoPresetAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "PresetToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String presetToken,
        @WebParam(name = "Speed", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        PTZSpeed speed,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GotoPresetResponse> asyncHandler);

    /**
     * 
     *         Operation to go to a saved preset position for the
     *         PTZNode in the selected profile. The operation is supported if there is
     *         support for at least on PTZ preset by the PTZNode.
     * 
     * @param presetToken
     * @param speed
     * @param profileToken
     */
    @WebMethod(operationName = "GotoPreset", action = "http://www.onvif.org/ver20/ptz/wsdl/GotoPreset")
    @RequestWrapper(localName = "GotoPreset", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GotoPreset")
    @ResponseWrapper(localName = "GotoPresetResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GotoPresetResponse")
    public void gotoPreset(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "PresetToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String presetToken,
        @WebParam(name = "Speed", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        PTZSpeed speed);

    /**
     * 
     * 				Operation to request PTZ status for the Node in the
     * 				selected profile.
     * 
     * @param profileToken
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver20.ptz.wsdl.GetStatusResponse>
     */
    @WebMethod(operationName = "GetStatus", action = "http://www.onvif.org/ver20/ptz/wsdl/GetStatus")
    @RequestWrapper(localName = "GetStatus", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetStatus")
    @ResponseWrapper(localName = "GetStatusResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetStatusResponse")
    public Response<GetStatusResponse> getStatusAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken);

    /**
     * 
     * 				Operation to request PTZ status for the Node in the
     * 				selected profile.
     * 
     * @param asyncHandler
     * @param profileToken
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetStatus", action = "http://www.onvif.org/ver20/ptz/wsdl/GetStatus")
    @RequestWrapper(localName = "GetStatus", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetStatus")
    @ResponseWrapper(localName = "GetStatusResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetStatusResponse")
    public Future<?> getStatusAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetStatusResponse> asyncHandler);

    /**
     * 
     * 				Operation to request PTZ status for the Node in the
     * 				selected profile.
     * 
     * @param profileToken
     * @return
     *     returns org.onvif.ver10.schema.PTZStatus
     */
    @WebMethod(operationName = "GetStatus", action = "http://www.onvif.org/ver20/ptz/wsdl/GetStatus")
    @WebResult(name = "PTZStatus", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
    @RequestWrapper(localName = "GetStatus", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetStatus")
    @ResponseWrapper(localName = "GetStatusResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetStatusResponse")
    public PTZStatus getStatus(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken);

    /**
     * 
     * @param ptzConfigurationToken
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver20.ptz.wsdl.GetConfigurationResponse>
     */
    @WebMethod(operationName = "GetConfiguration", action = "http://www.onvif.org/ver20/ptz/wsdl/GetConfiguration")
    @RequestWrapper(localName = "GetConfiguration", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetConfiguration")
    @ResponseWrapper(localName = "GetConfigurationResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetConfigurationResponse")
    public Response<GetConfigurationResponse> getConfigurationAsync(
        @WebParam(name = "PTZConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String ptzConfigurationToken);

    /**
     * 
     * @param asyncHandler
     * @param ptzConfigurationToken
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetConfiguration", action = "http://www.onvif.org/ver20/ptz/wsdl/GetConfiguration")
    @RequestWrapper(localName = "GetConfiguration", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetConfiguration")
    @ResponseWrapper(localName = "GetConfigurationResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetConfigurationResponse")
    public Future<?> getConfigurationAsync(
        @WebParam(name = "PTZConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String ptzConfigurationToken,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetConfigurationResponse> asyncHandler);

    /**
     * 
     * @param ptzConfigurationToken
     * @return
     *     returns org.onvif.ver10.schema.PTZConfiguration
     */
    @WebMethod(operationName = "GetConfiguration", action = "http://www.onvif.org/ver20/ptz/wsdl/GetConfiguration")
    @WebResult(name = "PTZConfiguration", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
    @RequestWrapper(localName = "GetConfiguration", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetConfiguration")
    @ResponseWrapper(localName = "GetConfigurationResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetConfigurationResponse")
    public PTZConfiguration getConfiguration(
        @WebParam(name = "PTZConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String ptzConfigurationToken);

    /**
     * 
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver20.ptz.wsdl.GetNodesResponse>
     */
    @WebMethod(operationName = "GetNodes", action = "http://www.onvif.org/ver20/ptz/wsdl/GetNodes")
    @RequestWrapper(localName = "GetNodes", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetNodes")
    @ResponseWrapper(localName = "GetNodesResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetNodesResponse")
    public Response<GetNodesResponse> getNodesAsync();

    /**
     * 
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetNodes", action = "http://www.onvif.org/ver20/ptz/wsdl/GetNodes")
    @RequestWrapper(localName = "GetNodes", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetNodes")
    @ResponseWrapper(localName = "GetNodesResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetNodesResponse")
    public Future<?> getNodesAsync(
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetNodesResponse> asyncHandler);

    /**
     * 
     * @return
     *     returns java.util.List<org.onvif.ver10.schema.PTZNode>
     */
    @WebMethod(operationName = "GetNodes", action = "http://www.onvif.org/ver20/ptz/wsdl/GetNodes")
    @WebResult(name = "PTZNode", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
    @RequestWrapper(localName = "GetNodes", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetNodes")
    @ResponseWrapper(localName = "GetNodesResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetNodesResponse")
    public List<PTZNode> getNodes();

    /**
     * Get a specific PTZ Node identified by a reference
     *         token or a name.
     * 	  
     * 
     * @param nodeToken
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver20.ptz.wsdl.GetNodeResponse>
     */
    @WebMethod(operationName = "GetNode", action = "http://www.onvif.org/ver20/ptz/wsdl/GetNode")
    @RequestWrapper(localName = "GetNode", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetNode")
    @ResponseWrapper(localName = "GetNodeResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetNodeResponse")
    public Response<GetNodeResponse> getNodeAsync(
        @WebParam(name = "NodeToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String nodeToken);

    /**
     * Get a specific PTZ Node identified by a reference
     *         token or a name.
     * 	  
     * 
     * @param asyncHandler
     * @param nodeToken
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetNode", action = "http://www.onvif.org/ver20/ptz/wsdl/GetNode")
    @RequestWrapper(localName = "GetNode", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetNode")
    @ResponseWrapper(localName = "GetNodeResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetNodeResponse")
    public Future<?> getNodeAsync(
        @WebParam(name = "NodeToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String nodeToken,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetNodeResponse> asyncHandler);

    /**
     * Get a specific PTZ Node identified by a reference
     *         token or a name.
     * 	  
     * 
     * @param nodeToken
     * @return
     *     returns org.onvif.ver10.schema.PTZNode
     */
    @WebMethod(operationName = "GetNode", action = "http://www.onvif.org/ver20/ptz/wsdl/GetNode")
    @WebResult(name = "PTZNode", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
    @RequestWrapper(localName = "GetNode", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetNode")
    @ResponseWrapper(localName = "GetNodeResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetNodeResponse")
    public PTZNode getNode(
        @WebParam(name = "NodeToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String nodeToken);

    /**
     * 
     *         Set/update a existing PTZConfiguration on the device.
     *       
     * 
     * @param forcePersistence
     * @param ptzConfiguration
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver20.ptz.wsdl.SetConfigurationResponse>
     */
    @WebMethod(operationName = "SetConfiguration", action = "http://www.onvif.org/ver20/ptz/wsdl/SetConfiguration")
    @RequestWrapper(localName = "SetConfiguration", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.SetConfiguration")
    @ResponseWrapper(localName = "SetConfigurationResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.SetConfigurationResponse")
    public Response<SetConfigurationResponse> setConfigurationAsync(
        @WebParam(name = "PTZConfiguration", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        PTZConfiguration ptzConfiguration,
        @WebParam(name = "ForcePersistence", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        boolean forcePersistence);

    /**
     * 
     *         Set/update a existing PTZConfiguration on the device.
     *       
     * 
     * @param forcePersistence
     * @param asyncHandler
     * @param ptzConfiguration
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "SetConfiguration", action = "http://www.onvif.org/ver20/ptz/wsdl/SetConfiguration")
    @RequestWrapper(localName = "SetConfiguration", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.SetConfiguration")
    @ResponseWrapper(localName = "SetConfigurationResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.SetConfigurationResponse")
    public Future<?> setConfigurationAsync(
        @WebParam(name = "PTZConfiguration", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        PTZConfiguration ptzConfiguration,
        @WebParam(name = "ForcePersistence", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        boolean forcePersistence,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<SetConfigurationResponse> asyncHandler);

    /**
     * 
     *         Set/update a existing PTZConfiguration on the device.
     *       
     * 
     * @param forcePersistence
     * @param ptzConfiguration
     */
    @WebMethod(operationName = "SetConfiguration", action = "http://www.onvif.org/ver20/ptz/wsdl/SetConfiguration")
    @RequestWrapper(localName = "SetConfiguration", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.SetConfiguration")
    @ResponseWrapper(localName = "SetConfigurationResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.SetConfigurationResponse")
    public void setConfiguration(
        @WebParam(name = "PTZConfiguration", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        PTZConfiguration ptzConfiguration,
        @WebParam(name = "ForcePersistence", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        boolean forcePersistence);

    /**
     * 
     * 				List supported coordinate systems including their range limitations. Therefore, the options
     * 				MAY differ depending on whether the PTZ Configuration is assigned to a Profile containing a
     * 				Video Source Configuration. In that case, the options may additionally contain coordinate
     * 				systems referring to the image coordinate system described by the Video Source
     * 				Configuration. If the PTZ Node supports continuous movements, it shall return a Timeout Range within
     * 				which Timeouts are accepted by the PTZ Node.				
     * 			
     * 
     * @param configurationToken
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver20.ptz.wsdl.GetConfigurationOptionsResponse>
     */
    @WebMethod(operationName = "GetConfigurationOptions", action = "http://www.onvif.org/ver20/ptz/wsdl/GetConfigurationOptions")
    @RequestWrapper(localName = "GetConfigurationOptions", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetConfigurationOptions")
    @ResponseWrapper(localName = "GetConfigurationOptionsResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetConfigurationOptionsResponse")
    public Response<GetConfigurationOptionsResponse> getConfigurationOptionsAsync(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String configurationToken);

    /**
     * 
     * 				List supported coordinate systems including their range limitations. Therefore, the options
     * 				MAY differ depending on whether the PTZ Configuration is assigned to a Profile containing a
     * 				Video Source Configuration. In that case, the options may additionally contain coordinate
     * 				systems referring to the image coordinate system described by the Video Source
     * 				Configuration. If the PTZ Node supports continuous movements, it shall return a Timeout Range within
     * 				which Timeouts are accepted by the PTZ Node.				
     * 			
     * 
     * @param configurationToken
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetConfigurationOptions", action = "http://www.onvif.org/ver20/ptz/wsdl/GetConfigurationOptions")
    @RequestWrapper(localName = "GetConfigurationOptions", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetConfigurationOptions")
    @ResponseWrapper(localName = "GetConfigurationOptionsResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetConfigurationOptionsResponse")
    public Future<?> getConfigurationOptionsAsync(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String configurationToken,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetConfigurationOptionsResponse> asyncHandler);

    /**
     * 
     * 				List supported coordinate systems including their range limitations. Therefore, the options
     * 				MAY differ depending on whether the PTZ Configuration is assigned to a Profile containing a
     * 				Video Source Configuration. In that case, the options may additionally contain coordinate
     * 				systems referring to the image coordinate system described by the Video Source
     * 				Configuration. If the PTZ Node supports continuous movements, it shall return a Timeout Range within
     * 				which Timeouts are accepted by the PTZ Node.				
     * 			
     * 
     * @param configurationToken
     * @return
     *     returns org.onvif.ver10.schema.PTZConfigurationOptions
     */
    @WebMethod(operationName = "GetConfigurationOptions", action = "http://www.onvif.org/ver20/ptz/wsdl/GetConfigurationOptions")
    @WebResult(name = "PTZConfigurationOptions", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
    @RequestWrapper(localName = "GetConfigurationOptions", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetConfigurationOptions")
    @ResponseWrapper(localName = "GetConfigurationOptionsResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetConfigurationOptionsResponse")
    public PTZConfigurationOptions getConfigurationOptions(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String configurationToken);

    /**
     * 
     *         Operation to move the PTZ device to it's "home" position. The operation is supported if the HomeSupported element in the PTZNode is true.
     * 
     * @param speed
     * @param profileToken
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver20.ptz.wsdl.GotoHomePositionResponse>
     */
    @WebMethod(operationName = "GotoHomePosition", action = "http://www.onvif.org/ver20/ptz/wsdl/GotoHomePosition")
    @RequestWrapper(localName = "GotoHomePosition", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GotoHomePosition")
    @ResponseWrapper(localName = "GotoHomePositionResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GotoHomePositionResponse")
    public Response<GotoHomePositionResponse> gotoHomePositionAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "Speed", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        PTZSpeed speed);

    /**
     * 
     *         Operation to move the PTZ device to it's "home" position. The operation is supported if the HomeSupported element in the PTZNode is true.
     * 
     * @param speed
     * @param asyncHandler
     * @param profileToken
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GotoHomePosition", action = "http://www.onvif.org/ver20/ptz/wsdl/GotoHomePosition")
    @RequestWrapper(localName = "GotoHomePosition", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GotoHomePosition")
    @ResponseWrapper(localName = "GotoHomePositionResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GotoHomePositionResponse")
    public Future<?> gotoHomePositionAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "Speed", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        PTZSpeed speed,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GotoHomePositionResponse> asyncHandler);

    /**
     * 
     *         Operation to move the PTZ device to it's "home" position. The operation is supported if the HomeSupported element in the PTZNode is true.
     * 
     * @param speed
     * @param profileToken
     */
    @WebMethod(operationName = "GotoHomePosition", action = "http://www.onvif.org/ver20/ptz/wsdl/GotoHomePosition")
    @RequestWrapper(localName = "GotoHomePosition", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GotoHomePosition")
    @ResponseWrapper(localName = "GotoHomePositionResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GotoHomePositionResponse")
    public void gotoHomePosition(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "Speed", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        PTZSpeed speed);

    /**
     * Operation to save current position as the home position.
     * 				The SetHomePosition command returns with a failure if the ¡°home¡± position is fixed and
     * 				cannot be overwritten. If the SetHomePosition is successful, it is possible to recall the
     * 				Home Position with the GotoHomePosition command.
     * 
     * @param profileToken
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver20.ptz.wsdl.SetHomePositionResponse>
     */
    @WebMethod(operationName = "SetHomePosition", action = "http://www.onvif.org/ver20/ptz/wsdl/SetHomePosition")
    @RequestWrapper(localName = "SetHomePosition", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.SetHomePosition")
    @ResponseWrapper(localName = "SetHomePositionResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.SetHomePositionResponse")
    public Response<SetHomePositionResponse> setHomePositionAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken);

    /**
     * Operation to save current position as the home position.
     * 				The SetHomePosition command returns with a failure if the ¡°home¡± position is fixed and
     * 				cannot be overwritten. If the SetHomePosition is successful, it is possible to recall the
     * 				Home Position with the GotoHomePosition command.
     * 
     * @param asyncHandler
     * @param profileToken
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "SetHomePosition", action = "http://www.onvif.org/ver20/ptz/wsdl/SetHomePosition")
    @RequestWrapper(localName = "SetHomePosition", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.SetHomePosition")
    @ResponseWrapper(localName = "SetHomePositionResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.SetHomePositionResponse")
    public Future<?> setHomePositionAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<SetHomePositionResponse> asyncHandler);

    /**
     * Operation to save current position as the home position.
     * 				The SetHomePosition command returns with a failure if the ¡°home¡± position is fixed and
     * 				cannot be overwritten. If the SetHomePosition is successful, it is possible to recall the
     * 				Home Position with the GotoHomePosition command.
     * 
     * @param profileToken
     */
    @WebMethod(operationName = "SetHomePosition", action = "http://www.onvif.org/ver20/ptz/wsdl/SetHomePosition")
    @RequestWrapper(localName = "SetHomePosition", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.SetHomePosition")
    @ResponseWrapper(localName = "SetHomePositionResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.SetHomePositionResponse")
    public void setHomePosition(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken);

    /**
     * Operation for continuous Pan/Tilt and Zoom movements. The operation is supported if the PTZNode supports at least one continuous Pan/Tilt or Zoom space. If the space argument is omitted, the default space set by the PTZConfiguration will be used.
     * 
     * @param velocity
     * @param profileToken
     * @param timeout
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver20.ptz.wsdl.ContinuousMoveResponse>
     */
    @WebMethod(operationName = "ContinuousMove", action = "http://www.onvif.org/ver20/ptz/wsdl/ContinuousMove")
    @RequestWrapper(localName = "ContinuousMove", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.ContinuousMove")
    @ResponseWrapper(localName = "ContinuousMoveResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.ContinuousMoveResponse")
    public Response<ContinuousMoveResponse> continuousMoveAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "Velocity", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        PTZSpeed velocity,
        @WebParam(name = "Timeout", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        Duration timeout);

    /**
     * Operation for continuous Pan/Tilt and Zoom movements. The operation is supported if the PTZNode supports at least one continuous Pan/Tilt or Zoom space. If the space argument is omitted, the default space set by the PTZConfiguration will be used.
     * 
     * @param asyncHandler
     * @param velocity
     * @param profileToken
     * @param timeout
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "ContinuousMove", action = "http://www.onvif.org/ver20/ptz/wsdl/ContinuousMove")
    @RequestWrapper(localName = "ContinuousMove", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.ContinuousMove")
    @ResponseWrapper(localName = "ContinuousMoveResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.ContinuousMoveResponse")
    public Future<?> continuousMoveAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "Velocity", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        PTZSpeed velocity,
        @WebParam(name = "Timeout", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        Duration timeout,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<ContinuousMoveResponse> asyncHandler);

    /**
     * Operation for continuous Pan/Tilt and Zoom movements. The operation is supported if the PTZNode supports at least one continuous Pan/Tilt or Zoom space. If the space argument is omitted, the default space set by the PTZConfiguration will be used.
     * 
     * @param velocity
     * @param profileToken
     * @param timeout
     */
    @WebMethod(operationName = "ContinuousMove", action = "http://www.onvif.org/ver20/ptz/wsdl/ContinuousMove")
    @RequestWrapper(localName = "ContinuousMove", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.ContinuousMove")
    @ResponseWrapper(localName = "ContinuousMoveResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.ContinuousMoveResponse")
    public void continuousMove(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "Velocity", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        PTZSpeed velocity,
        @WebParam(name = "Timeout", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        Duration timeout);

    /**
     * 
     * @param translation
     * @param speed
     * @param profileToken
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver20.ptz.wsdl.RelativeMoveResponse>
     */
    @WebMethod(operationName = "RelativeMove", action = "http://www.onvif.org/ver20/ptz/wsdl/RelativeMove")
    @RequestWrapper(localName = "RelativeMove", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.RelativeMove")
    @ResponseWrapper(localName = "RelativeMoveResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.RelativeMoveResponse")
    public Response<RelativeMoveResponse> relativeMoveAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "Translation", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        PTZVector translation,
        @WebParam(name = "Speed", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        PTZSpeed speed);

    /**
     * 
     * @param translation
     * @param speed
     * @param asyncHandler
     * @param profileToken
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "RelativeMove", action = "http://www.onvif.org/ver20/ptz/wsdl/RelativeMove")
    @RequestWrapper(localName = "RelativeMove", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.RelativeMove")
    @ResponseWrapper(localName = "RelativeMoveResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.RelativeMoveResponse")
    public Future<?> relativeMoveAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "Translation", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        PTZVector translation,
        @WebParam(name = "Speed", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        PTZSpeed speed,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<RelativeMoveResponse> asyncHandler);

    /**
     * 
     * @param translation
     * @param speed
     * @param profileToken
     */
    @WebMethod(operationName = "RelativeMove", action = "http://www.onvif.org/ver20/ptz/wsdl/RelativeMove")
    @RequestWrapper(localName = "RelativeMove", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.RelativeMove")
    @ResponseWrapper(localName = "RelativeMoveResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.RelativeMoveResponse")
    public void relativeMove(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "Translation", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        PTZVector translation,
        @WebParam(name = "Speed", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        PTZSpeed speed);

    /**
     * 
     *         Operation to send auxiliary commands to the PTZ device
     *         mapped by the PTZNode in the selected profile. The
     *         operation is supported
     *         if the AuxiliarySupported element of the PTZNode is true
     *       
     * 
     * @param auxiliaryData
     * @param profileToken
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver20.ptz.wsdl.SendAuxiliaryCommandResponse>
     */
    @WebMethod(operationName = "SendAuxiliaryCommand", action = "http://www.onvif.org/ver20/ptz/wsdl/SendAuxiliaryCommand")
    @RequestWrapper(localName = "SendAuxiliaryCommand", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.SendAuxiliaryCommand")
    @ResponseWrapper(localName = "SendAuxiliaryCommandResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.SendAuxiliaryCommandResponse")
    public Response<SendAuxiliaryCommandResponse> sendAuxiliaryCommandAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "AuxiliaryData", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String auxiliaryData);

    /**
     * 
     *         Operation to send auxiliary commands to the PTZ device
     *         mapped by the PTZNode in the selected profile. The
     *         operation is supported
     *         if the AuxiliarySupported element of the PTZNode is true
     *       
     * 
     * @param auxiliaryData
     * @param asyncHandler
     * @param profileToken
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "SendAuxiliaryCommand", action = "http://www.onvif.org/ver20/ptz/wsdl/SendAuxiliaryCommand")
    @RequestWrapper(localName = "SendAuxiliaryCommand", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.SendAuxiliaryCommand")
    @ResponseWrapper(localName = "SendAuxiliaryCommandResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.SendAuxiliaryCommandResponse")
    public Future<?> sendAuxiliaryCommandAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "AuxiliaryData", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String auxiliaryData,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<SendAuxiliaryCommandResponse> asyncHandler);

    /**
     * 
     *         Operation to send auxiliary commands to the PTZ device
     *         mapped by the PTZNode in the selected profile. The
     *         operation is supported
     *         if the AuxiliarySupported element of the PTZNode is true
     *       
     * 
     * @param auxiliaryData
     * @param profileToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendAuxiliaryCommand", action = "http://www.onvif.org/ver20/ptz/wsdl/SendAuxiliaryCommand")
    @WebResult(name = "AuxiliaryResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
    @RequestWrapper(localName = "SendAuxiliaryCommand", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.SendAuxiliaryCommand")
    @ResponseWrapper(localName = "SendAuxiliaryCommandResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.SendAuxiliaryCommandResponse")
    public String sendAuxiliaryCommand(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "AuxiliaryData", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String auxiliaryData);

    /**
     * 
     * @param position
     * @param speed
     * @param profileToken
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver20.ptz.wsdl.AbsoluteMoveResponse>
     */
    @WebMethod(operationName = "AbsoluteMove", action = "http://www.onvif.org/ver20/ptz/wsdl/AbsoluteMove")
    @RequestWrapper(localName = "AbsoluteMove", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.AbsoluteMove")
    @ResponseWrapper(localName = "AbsoluteMoveResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.AbsoluteMoveResponse")
    public Response<AbsoluteMoveResponse> absoluteMoveAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "Position", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        PTZVector position,
        @WebParam(name = "Speed", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        PTZSpeed speed);

    /**
     * 
     * @param position
     * @param speed
     * @param asyncHandler
     * @param profileToken
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "AbsoluteMove", action = "http://www.onvif.org/ver20/ptz/wsdl/AbsoluteMove")
    @RequestWrapper(localName = "AbsoluteMove", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.AbsoluteMove")
    @ResponseWrapper(localName = "AbsoluteMoveResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.AbsoluteMoveResponse")
    public Future<?> absoluteMoveAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "Position", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        PTZVector position,
        @WebParam(name = "Speed", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        PTZSpeed speed,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<AbsoluteMoveResponse> asyncHandler);

    /**
     * 
     * @param position
     * @param speed
     * @param profileToken
     */
    @WebMethod(operationName = "AbsoluteMove", action = "http://www.onvif.org/ver20/ptz/wsdl/AbsoluteMove")
    @RequestWrapper(localName = "AbsoluteMove", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.AbsoluteMove")
    @ResponseWrapper(localName = "AbsoluteMoveResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.AbsoluteMoveResponse")
    public void absoluteMove(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "Position", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        PTZVector position,
        @WebParam(name = "Speed", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        PTZSpeed speed);

    /**
     * 
     * @param speed
     * @param target
     * @param areaHeight
     * @param profileToken
     * @param areaWidth
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver20.ptz.wsdl.GeoMoveResponse>
     */
    @WebMethod(operationName = "GeoMove", action = "http://www.onvif.org/ver20/ptz/wsdl/GeoMove")
    @RequestWrapper(localName = "GeoMove", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GeoMove")
    @ResponseWrapper(localName = "GeoMoveResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GeoMoveResponse")
    public Response<GeoMoveResponse> geoMoveAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "Target", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        GeoLocation target,
        @WebParam(name = "Speed", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        PTZSpeed speed,
        @WebParam(name = "AreaHeight", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        Float areaHeight,
        @WebParam(name = "AreaWidth", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        Float areaWidth);

    /**
     * 
     * @param speed
     * @param target
     * @param asyncHandler
     * @param areaHeight
     * @param profileToken
     * @param areaWidth
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GeoMove", action = "http://www.onvif.org/ver20/ptz/wsdl/GeoMove")
    @RequestWrapper(localName = "GeoMove", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GeoMove")
    @ResponseWrapper(localName = "GeoMoveResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GeoMoveResponse")
    public Future<?> geoMoveAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "Target", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        GeoLocation target,
        @WebParam(name = "Speed", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        PTZSpeed speed,
        @WebParam(name = "AreaHeight", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        Float areaHeight,
        @WebParam(name = "AreaWidth", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        Float areaWidth,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GeoMoveResponse> asyncHandler);

    /**
     * 
     * @param speed
     * @param target
     * @param areaHeight
     * @param profileToken
     * @param areaWidth
     */
    @WebMethod(operationName = "GeoMove", action = "http://www.onvif.org/ver20/ptz/wsdl/GeoMove")
    @RequestWrapper(localName = "GeoMove", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GeoMove")
    @ResponseWrapper(localName = "GeoMoveResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GeoMoveResponse")
    public void geoMove(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "Target", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        GeoLocation target,
        @WebParam(name = "Speed", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        PTZSpeed speed,
        @WebParam(name = "AreaHeight", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        Float areaHeight,
        @WebParam(name = "AreaWidth", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        Float areaWidth);

    /**
     * Operation to stop ongoing pan, tilt and zoom movements of absolute relative and continuous type.
     * If no stop argument for pan, tilt or zoom is set, the device will stop all ongoing pan, tilt and zoom movements.
     * 
     * @param zoom
     * @param profileToken
     * @param panTilt
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver20.ptz.wsdl.StopResponse>
     */
    @WebMethod(operationName = "Stop", action = "http://www.onvif.org/ver20/ptz/wsdl/Stop")
    @RequestWrapper(localName = "Stop", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.Stop")
    @ResponseWrapper(localName = "StopResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.StopResponse")
    public Response<StopResponse> stopAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "PanTilt", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        Boolean panTilt,
        @WebParam(name = "Zoom", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        Boolean zoom);

    /**
     * Operation to stop ongoing pan, tilt and zoom movements of absolute relative and continuous type.
     * If no stop argument for pan, tilt or zoom is set, the device will stop all ongoing pan, tilt and zoom movements.
     * 
     * @param zoom
     * @param asyncHandler
     * @param profileToken
     * @param panTilt
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "Stop", action = "http://www.onvif.org/ver20/ptz/wsdl/Stop")
    @RequestWrapper(localName = "Stop", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.Stop")
    @ResponseWrapper(localName = "StopResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.StopResponse")
    public Future<?> stopAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "PanTilt", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        Boolean panTilt,
        @WebParam(name = "Zoom", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        Boolean zoom,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<StopResponse> asyncHandler);

    /**
     * Operation to stop ongoing pan, tilt and zoom movements of absolute relative and continuous type.
     * If no stop argument for pan, tilt or zoom is set, the device will stop all ongoing pan, tilt and zoom movements.
     * 
     * @param zoom
     * @param profileToken
     * @param panTilt
     */
    @WebMethod(operationName = "Stop", action = "http://www.onvif.org/ver20/ptz/wsdl/Stop")
    @RequestWrapper(localName = "Stop", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.Stop")
    @ResponseWrapper(localName = "StopResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.StopResponse")
    public void stop(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "PanTilt", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        Boolean panTilt,
        @WebParam(name = "Zoom", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        Boolean zoom);

    /**
     * Operation to request PTZ preset tours in the selected media profiles.
     * 
     * @param profileToken
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver20.ptz.wsdl.GetPresetToursResponse>
     */
    @WebMethod(operationName = "GetPresetTours", action = "http://www.onvif.org/ver20/ptz/wsdl/GetPresetTours")
    @RequestWrapper(localName = "GetPresetTours", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetPresetTours")
    @ResponseWrapper(localName = "GetPresetToursResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetPresetToursResponse")
    public Response<GetPresetToursResponse> getPresetToursAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken);

    /**
     * Operation to request PTZ preset tours in the selected media profiles.
     * 
     * @param asyncHandler
     * @param profileToken
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetPresetTours", action = "http://www.onvif.org/ver20/ptz/wsdl/GetPresetTours")
    @RequestWrapper(localName = "GetPresetTours", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetPresetTours")
    @ResponseWrapper(localName = "GetPresetToursResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetPresetToursResponse")
    public Future<?> getPresetToursAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetPresetToursResponse> asyncHandler);

    /**
     * Operation to request PTZ preset tours in the selected media profiles.
     * 
     * @param profileToken
     * @return
     *     returns java.util.List<org.onvif.ver10.schema.PresetTour>
     */
    @WebMethod(operationName = "GetPresetTours", action = "http://www.onvif.org/ver20/ptz/wsdl/GetPresetTours")
    @WebResult(name = "PresetTour", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
    @RequestWrapper(localName = "GetPresetTours", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetPresetTours")
    @ResponseWrapper(localName = "GetPresetToursResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetPresetToursResponse")
    public List<PresetTour> getPresetTours(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken);

    /**
     * Operation to request a specific PTZ preset tour in the selected media profile.
     * 
     * @param presetTourToken
     * @param profileToken
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver20.ptz.wsdl.GetPresetTourResponse>
     */
    @WebMethod(operationName = "GetPresetTour", action = "http://www.onvif.org/ver20/ptz/wsdl/GetPresetTour")
    @RequestWrapper(localName = "GetPresetTour", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetPresetTour")
    @ResponseWrapper(localName = "GetPresetTourResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetPresetTourResponse")
    public Response<GetPresetTourResponse> getPresetTourAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "PresetTourToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String presetTourToken);

    /**
     * Operation to request a specific PTZ preset tour in the selected media profile.
     * 
     * @param presetTourToken
     * @param asyncHandler
     * @param profileToken
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetPresetTour", action = "http://www.onvif.org/ver20/ptz/wsdl/GetPresetTour")
    @RequestWrapper(localName = "GetPresetTour", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetPresetTour")
    @ResponseWrapper(localName = "GetPresetTourResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetPresetTourResponse")
    public Future<?> getPresetTourAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "PresetTourToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String presetTourToken,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetPresetTourResponse> asyncHandler);

    /**
     * Operation to request a specific PTZ preset tour in the selected media profile.
     * 
     * @param presetTourToken
     * @param profileToken
     * @return
     *     returns org.onvif.ver10.schema.PresetTour
     */
    @WebMethod(operationName = "GetPresetTour", action = "http://www.onvif.org/ver20/ptz/wsdl/GetPresetTour")
    @WebResult(name = "PresetTour", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
    @RequestWrapper(localName = "GetPresetTour", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetPresetTour")
    @ResponseWrapper(localName = "GetPresetTourResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetPresetTourResponse")
    public PresetTour getPresetTour(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "PresetTourToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String presetTourToken);

    /**
     * Operation to request available options to configure PTZ preset tour.
     * 
     * @param presetTourToken
     * @param profileToken
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver20.ptz.wsdl.GetPresetTourOptionsResponse>
     */
    @WebMethod(operationName = "GetPresetTourOptions", action = "http://www.onvif.org/ver20/ptz/wsdl/GetPresetTourOptions")
    @RequestWrapper(localName = "GetPresetTourOptions", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetPresetTourOptions")
    @ResponseWrapper(localName = "GetPresetTourOptionsResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetPresetTourOptionsResponse")
    public Response<GetPresetTourOptionsResponse> getPresetTourOptionsAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "PresetTourToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String presetTourToken);

    /**
     * Operation to request available options to configure PTZ preset tour.
     * 
     * @param presetTourToken
     * @param asyncHandler
     * @param profileToken
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetPresetTourOptions", action = "http://www.onvif.org/ver20/ptz/wsdl/GetPresetTourOptions")
    @RequestWrapper(localName = "GetPresetTourOptions", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetPresetTourOptions")
    @ResponseWrapper(localName = "GetPresetTourOptionsResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetPresetTourOptionsResponse")
    public Future<?> getPresetTourOptionsAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "PresetTourToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String presetTourToken,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetPresetTourOptionsResponse> asyncHandler);

    /**
     * Operation to request available options to configure PTZ preset tour.
     * 
     * @param presetTourToken
     * @param profileToken
     * @return
     *     returns org.onvif.ver10.schema.PTZPresetTourOptions
     */
    @WebMethod(operationName = "GetPresetTourOptions", action = "http://www.onvif.org/ver20/ptz/wsdl/GetPresetTourOptions")
    @WebResult(name = "Options", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
    @RequestWrapper(localName = "GetPresetTourOptions", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetPresetTourOptions")
    @ResponseWrapper(localName = "GetPresetTourOptionsResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetPresetTourOptionsResponse")
    public PTZPresetTourOptions getPresetTourOptions(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "PresetTourToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String presetTourToken);

    /**
     * Operation to create a preset tour for the selected media profile.
     * 
     * @param profileToken
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver20.ptz.wsdl.CreatePresetTourResponse>
     */
    @WebMethod(operationName = "CreatePresetTour", action = "http://www.onvif.org/ver20/ptz/wsdl/CreatePresetTour")
    @RequestWrapper(localName = "CreatePresetTour", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.CreatePresetTour")
    @ResponseWrapper(localName = "CreatePresetTourResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.CreatePresetTourResponse")
    public Response<CreatePresetTourResponse> createPresetTourAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken);

    /**
     * Operation to create a preset tour for the selected media profile.
     * 
     * @param asyncHandler
     * @param profileToken
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "CreatePresetTour", action = "http://www.onvif.org/ver20/ptz/wsdl/CreatePresetTour")
    @RequestWrapper(localName = "CreatePresetTour", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.CreatePresetTour")
    @ResponseWrapper(localName = "CreatePresetTourResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.CreatePresetTourResponse")
    public Future<?> createPresetTourAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<CreatePresetTourResponse> asyncHandler);

    /**
     * Operation to create a preset tour for the selected media profile.
     * 
     * @param profileToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreatePresetTour", action = "http://www.onvif.org/ver20/ptz/wsdl/CreatePresetTour")
    @WebResult(name = "PresetTourToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
    @RequestWrapper(localName = "CreatePresetTour", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.CreatePresetTour")
    @ResponseWrapper(localName = "CreatePresetTourResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.CreatePresetTourResponse")
    public String createPresetTour(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken);

    /**
     * Operation to modify a preset tour for the selected media profile.
     * 
     * @param profileToken
     * @param presetTour
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver20.ptz.wsdl.ModifyPresetTourResponse>
     */
    @WebMethod(operationName = "ModifyPresetTour", action = "http://www.onvif.org/ver20/ptz/wsdl/ModifyPresetTour")
    @RequestWrapper(localName = "ModifyPresetTour", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.ModifyPresetTour")
    @ResponseWrapper(localName = "ModifyPresetTourResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.ModifyPresetTourResponse")
    public Response<ModifyPresetTourResponse> modifyPresetTourAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "PresetTour", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        PresetTour presetTour);

    /**
     * Operation to modify a preset tour for the selected media profile.
     * 
     * @param asyncHandler
     * @param profileToken
     * @param presetTour
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "ModifyPresetTour", action = "http://www.onvif.org/ver20/ptz/wsdl/ModifyPresetTour")
    @RequestWrapper(localName = "ModifyPresetTour", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.ModifyPresetTour")
    @ResponseWrapper(localName = "ModifyPresetTourResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.ModifyPresetTourResponse")
    public Future<?> modifyPresetTourAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "PresetTour", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        PresetTour presetTour,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<ModifyPresetTourResponse> asyncHandler);

    /**
     * Operation to modify a preset tour for the selected media profile.
     * 
     * @param profileToken
     * @param presetTour
     */
    @WebMethod(operationName = "ModifyPresetTour", action = "http://www.onvif.org/ver20/ptz/wsdl/ModifyPresetTour")
    @RequestWrapper(localName = "ModifyPresetTour", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.ModifyPresetTour")
    @ResponseWrapper(localName = "ModifyPresetTourResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.ModifyPresetTourResponse")
    public void modifyPresetTour(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "PresetTour", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        PresetTour presetTour);

    /**
     * Operation to perform specific operation on the preset tour in selected media profile.
     * 
     * @param operation
     * @param presetTourToken
     * @param profileToken
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver20.ptz.wsdl.OperatePresetTourResponse>
     */
    @WebMethod(operationName = "OperatePresetTour", action = "http://www.onvif.org/ver20/ptz/wsdl/OperatePresetTour")
    @RequestWrapper(localName = "OperatePresetTour", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.OperatePresetTour")
    @ResponseWrapper(localName = "OperatePresetTourResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.OperatePresetTourResponse")
    public Response<OperatePresetTourResponse> operatePresetTourAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "PresetTourToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String presetTourToken,
        @WebParam(name = "Operation", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        PTZPresetTourOperation operation);

    /**
     * Operation to perform specific operation on the preset tour in selected media profile.
     * 
     * @param operation
     * @param presetTourToken
     * @param asyncHandler
     * @param profileToken
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "OperatePresetTour", action = "http://www.onvif.org/ver20/ptz/wsdl/OperatePresetTour")
    @RequestWrapper(localName = "OperatePresetTour", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.OperatePresetTour")
    @ResponseWrapper(localName = "OperatePresetTourResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.OperatePresetTourResponse")
    public Future<?> operatePresetTourAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "PresetTourToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String presetTourToken,
        @WebParam(name = "Operation", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        PTZPresetTourOperation operation,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<OperatePresetTourResponse> asyncHandler);

    /**
     * Operation to perform specific operation on the preset tour in selected media profile.
     * 
     * @param operation
     * @param presetTourToken
     * @param profileToken
     */
    @WebMethod(operationName = "OperatePresetTour", action = "http://www.onvif.org/ver20/ptz/wsdl/OperatePresetTour")
    @RequestWrapper(localName = "OperatePresetTour", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.OperatePresetTour")
    @ResponseWrapper(localName = "OperatePresetTourResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.OperatePresetTourResponse")
    public void operatePresetTour(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "PresetTourToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String presetTourToken,
        @WebParam(name = "Operation", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        PTZPresetTourOperation operation);

    /**
     * Operation to delete a specific preset tour from the media profile.
     * 
     * @param presetTourToken
     * @param profileToken
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver20.ptz.wsdl.RemovePresetTourResponse>
     */
    @WebMethod(operationName = "RemovePresetTour", action = "http://www.onvif.org/ver20/ptz/wsdl/RemovePresetTour")
    @RequestWrapper(localName = "RemovePresetTour", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.RemovePresetTour")
    @ResponseWrapper(localName = "RemovePresetTourResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.RemovePresetTourResponse")
    public Response<RemovePresetTourResponse> removePresetTourAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "PresetTourToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String presetTourToken);

    /**
     * Operation to delete a specific preset tour from the media profile.
     * 
     * @param presetTourToken
     * @param asyncHandler
     * @param profileToken
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "RemovePresetTour", action = "http://www.onvif.org/ver20/ptz/wsdl/RemovePresetTour")
    @RequestWrapper(localName = "RemovePresetTour", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.RemovePresetTour")
    @ResponseWrapper(localName = "RemovePresetTourResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.RemovePresetTourResponse")
    public Future<?> removePresetTourAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "PresetTourToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String presetTourToken,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<RemovePresetTourResponse> asyncHandler);

    /**
     * Operation to delete a specific preset tour from the media profile.
     * 
     * @param presetTourToken
     * @param profileToken
     */
    @WebMethod(operationName = "RemovePresetTour", action = "http://www.onvif.org/ver20/ptz/wsdl/RemovePresetTour")
    @RequestWrapper(localName = "RemovePresetTour", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.RemovePresetTour")
    @ResponseWrapper(localName = "RemovePresetTourResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.RemovePresetTourResponse")
    public void removePresetTour(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "PresetTourToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String presetTourToken);

    /**
     * 
     * @param profileToken
     * @return
     *     returns javax.xml.ws.Response<org.onvif.ver20.ptz.wsdl.GetCompatibleConfigurationsResponse>
     */
    @WebMethod(operationName = "GetCompatibleConfigurations", action = "http://www.onvif.org/ver20/ptz/wsdl/GetCompatibleConfigurations")
    @RequestWrapper(localName = "GetCompatibleConfigurations", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetCompatibleConfigurations")
    @ResponseWrapper(localName = "GetCompatibleConfigurationsResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetCompatibleConfigurationsResponse")
    public Response<GetCompatibleConfigurationsResponse> getCompatibleConfigurationsAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken);

    /**
     * 
     * @param asyncHandler
     * @param profileToken
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetCompatibleConfigurations", action = "http://www.onvif.org/ver20/ptz/wsdl/GetCompatibleConfigurations")
    @RequestWrapper(localName = "GetCompatibleConfigurations", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetCompatibleConfigurations")
    @ResponseWrapper(localName = "GetCompatibleConfigurationsResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetCompatibleConfigurationsResponse")
    public Future<?> getCompatibleConfigurationsAsync(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetCompatibleConfigurationsResponse> asyncHandler);

    /**
     * 
     * @param profileToken
     * @return
     *     returns java.util.List<org.onvif.ver10.schema.PTZConfiguration>
     */
    @WebMethod(operationName = "GetCompatibleConfigurations", action = "http://www.onvif.org/ver20/ptz/wsdl/GetCompatibleConfigurations")
    @WebResult(name = "PTZConfiguration", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
    @RequestWrapper(localName = "GetCompatibleConfigurations", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetCompatibleConfigurations")
    @ResponseWrapper(localName = "GetCompatibleConfigurationsResponse", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", className = "org.onvif.ver20.ptz.wsdl.GetCompatibleConfigurationsResponse")
    public List<PTZConfiguration> getCompatibleConfigurations(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl")
        String profileToken);

}
