
package org.onvif.ver20.ptz.wsdl;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PTZService", targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl", wsdlLocation = "classpath:wsdl/ptzProxy.wsdl")
public class PTZService
    extends Service
{

    private final static URL PTZSERVICE_WSDL_LOCATION;
    private final static WebServiceException PTZSERVICE_EXCEPTION;
    private final static QName PTZSERVICE_QNAME = new QName("http://www.onvif.org/ver20/ptz/wsdl", "PTZService");

    static {
        PTZSERVICE_WSDL_LOCATION = org.onvif.ver20.ptz.wsdl.PTZService.class.getResource("classpath:wsdl/ptzProxy.wsdl");
        WebServiceException e = null;
        if (PTZSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'classpath:wsdl/ptzProxy.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        PTZSERVICE_EXCEPTION = e;
    }

    public PTZService() {
        super(__getWsdlLocation(), PTZSERVICE_QNAME);
    }

    public PTZService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PTZSERVICE_QNAME, features);
    }

    public PTZService(URL wsdlLocation) {
        super(wsdlLocation, PTZSERVICE_QNAME);
    }

    public PTZService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PTZSERVICE_QNAME, features);
    }

    public PTZService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PTZService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PTZ
     */
    @WebEndpoint(name = "PTZServicePort")
    public PTZ getPTZServicePort() {
        return super.getPort(new QName("http://www.onvif.org/ver20/ptz/wsdl", "PTZServicePort"), PTZ.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PTZ
     */
    @WebEndpoint(name = "PTZServicePort")
    public PTZ getPTZServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.onvif.org/ver20/ptz/wsdl", "PTZServicePort"), PTZ.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PTZSERVICE_EXCEPTION!= null) {
            throw PTZSERVICE_EXCEPTION;
        }
        return PTZSERVICE_WSDL_LOCATION;
    }

}
